Script Name: -Sell in May, buy in September--Strategy
Author: DynamicSignalLab
Description: Dear TV'ers,

This script applies the classic traders mantra of "Sell in May, buy in September".  Not much else to it to be honest. Seems to work though :-).
PineScript code:

Pine Script™ strategy
"Sell in May, buy in September"-Strategy
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © DynamicSignalLab
//@version=5
strategy("Sell in May, buy in September Strategy", overlay=false)
longCondition = month==9
closecondition = month==5
if longCondition
    strategy.entry("long", strategy.long)
if closecondition
    strategy.close("long", when=closecondition)
Expand (15 lines)