Script Name: 80-20
Author: sachin06192
Description: Indicator which shows candles which have open or close in top or bottom 20% of the range.
PineScript code:

Pine Script™ strategy
80-20
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
//@version=5
//FxLowe - NR4 & NR7.
strategy(title = "80-20", overlay = true)
twenty = 0.2 * ( high - low)
triggerGreen = ((close >= high-twenty)) and ((open <= low+twenty))
triggerRed = (open >= high-twenty) and (close <= low+twenty)
//barcolor( trigger ? blue : na, offset = 0, editable = true, title = "trigger")
plotshape(triggerGreen, title= "triggerGreen", location=location.abovebar, color=color.blue, style=shape.arrowdown, text="")
plotshape(triggerRed, title= "triggerRed", location=location.abovebar, color=color.red, style=shape.arrowdown, text="")
Expand (12 lines)