Script Name: [tradinghook] - Renko Trend Reversal Strategy V2
Author: subhanahmed047
Description: Title: Renko Trend Reversal Strategy
Short Title: - Renko TRS

> Special thanks to  for manually calculating `renkoClose` and `renkoOpen` values in order to remove the infamous repaint issue

Description:

The Renko Trend Reversal Strategy ( - Renko TRS) is a powerful and original trading approach designed to identify trend reversals in financial markets using...
PineScript code:

Pine Script™ strategy
[tradinghook] - Renko Trend Reversal Strategy V2
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
//@version=5
strategy(title='[tradinghook] - Renko Trend Reversal Strategy', shorttitle='[tradinghook] - Renko TRS', overlay=true ,initial_capital = 100, commission_value = 0.05, default_qty_value = 5)
// INPUTS
renkoATRLength = input.int(10, minval=1, title='ATR Length')
stopLossPct = input.float(3, title='Stop Loss Percentage', step=0.1)
takeProfitPct = input.float(20, title='Take Profit Percentage', step=0.1)
startDate = input.time(timestamp("01 July 2023 00:00"), title="Start Date")
endDate = input.time(timestamp("31 Dec 2025 23:59"), title="End Date")
enableShorts = input.bool(true, title="Enable Shorts")
enableSignals = input.bool(true, title="Enable Buy/Sell Signals")
var float stopLossPrice = na
var float takeProfitPrice = na
atr = ta.atr(renkoATRLength)
// thanks to https://www.tradingview.com/script/2vKhpfVH-Renko-XZ/ for manually calculating renkoClose and renkoOpen in order to remove repaint
getRenkoClose() =>
    p1 = 0.0
    p1 := close > nz(p1[1]) + atr ? nz(p1[1]) + atr : close < nz(p1[1]) - atr ? nz(p1[1]) - atr : nz(p1[1])
    p1
calculateRenkoOpen() =>
    p3 = 0.0
    p3 := open > nz(p3[1]) + atr ? nz(p3[1]) + atr : open < nz(p3[1]) - atr ? nz(p3[1]) - atr : nz(p3[1])
    p3
getRenkoOpen() =>
    open_v = 0.0
    Br_2 = calculateRenkoOpen()
    open_v := calculateRenkoOpen() != calculateRenkoOpen()[1] ? Br_2[1] : nz(open_v[1])
    open_v
    
// Calculate Renko open and close values
renkoOpen = getRenkoOpen()
renkoClose = getRenkoClose()
// PLOTS
plotOpen = plot(renkoOpen, title="Renko Open", color=color.new(color.green, 100), style=plot.style_linebr)
plotClose = plot(renkoClose, title="Renko Close", color=color.new(color.red, 100), style=plot.style_linebr)
fill(plotOpen, plotClose, title="Area Fill", color=renkoClose < renkoOpen ? color.new(color.red, 70) : color.new(color.green, 70))
// SIGNALS
if (enableSignals) 
    isWithinTimeRange = time >= startDate and time <= endDate
    buySignal = ta.crossunder(renkoOpen, renkoClose) and isWithinTimeRange
    sellSignal = ta.crossover(renkoOpen, renkoClose) and isWithinTimeRange and enableShorts
    if (buySignal)
        stopLossPrice := renkoOpen * (1 - stopLossPct / 100)
        takeProfitPrice := renkoOpen * (1 + takeProfitPct / 100)
        strategy.entry("Long", strategy.long)
        strategy.exit("ExitLong", "Long", stop = stopLossPrice, limit = takeProfitPrice, comment="SL: " + str.tostring(stopLossPrice) + ", TP: " + str.tostring(takeProfitPrice))
    if (sellSignal)
        stopLossPrice := renkoOpen * (1 + stopLossPct / 100)
        takeProfitPrice := renkoOpen * (1 - takeProfitPct / 100)
        strategy.entry("Short", strategy.short)
        strategy.exit("ExitShort", "Short", stop = stopLossPrice, limit = takeProfitPrice, comment="SL: " + str.tostring(stopLossPrice) + ", TP: " + str.tostring(takeProfitPrice))
Expand (60 lines)