Script Name: BOLLY Bands
Author: bya5077
Description: This is a strategy using Bollinger Bands. The strategy is predicated around having low volatility in price action and then looking to capture a move when price starts to trend outside of the Bollinger bands. This strategy has only been backtested for 1 month but it has promising results so I will be sharing it looking for feedback. I run this strategy on the ERUSD...
PineScript code:

Pine Script™ strategy
BOLLY Bands
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
//@version=4
// Step 1) Define strategy settings
strategy(title="BOLLY Bands", overlay=true, pyramiding=4, initial_capital=100000, commission_type=strategy.commission.cash_per_order, commission_value=4, slippage=2)
// BOLLY 
length = input(22, minval=1)
src = input(ohlc4, title="Source")
mult = input(title="StdDev", type=input.float , defval=2.0, minval=0.001, maxval=50)
basis = sma(src, length)
dev = mult * stdev(src, length)
upper = basis + dev
lower = basis - dev
offset = input(type=input.integer, defval=0, title = "Offset", minval = -500, maxval = 500)
plot(basis, "Basis", color=#FF6D00, offset = offset)
p1 = plot(upper, "Upper", color=#2962FF, offset = offset)
p2 = plot(lower, "Lower", color=#2962FF, offset = offset)
fill(p1, p2, title = "Background", color=color.rgb(33, 150, 243, 95))
// Stop loss inputs
atrLen = input(title="ATR Length", type=input.integer, defval=10)
stopOffset = input(title="Stop Offset Multiple", type=input.float, defval=2, step=.25)
// Position sizing inputs
usePosSize = input(title="Use Position Sizing?", type=input.bool, defval=true)
maxRisk = input(title="Max Position Risk %", type=input.float, defval=2, step=.25)
maxExposure = input(title="Max Position Exposure %", type=input.float, defval=10, step=1)
marginPerc = input(title="Margin %", type=input.integer, defval=10)
atrValue = atr(atrLen)
t1 = time(timeframe.period, "0000-2400")
bgcolor(t1 ? color.blue : na)
tradeWindow = t1
// Calculate position size
riskEquity = maxRisk * 0.01 * strategy.equity
riskTrade = atrValue * stopOffset * syminfo.pointvalue
maxPos = maxExposure * 0.01 * strategy.equity / 
   (marginPerc * 0.01 * close * syminfo.pointvalue)
posSize = usePosSize ? min(floor(riskEquity / riskTrade), maxPos) : 1
distance = upper - lower
enterLong = close < lower and tradeWindow and dev < 0.00025
enterShort = close > upper and tradeWindow and dev < 0.00025
tp=input(title = "Take Profit (PIPs)", type=input.integer, defval=300, step=25)
sl=input(title = "Stop Loss (PIPs)", type=input.integer, defval=100, step=25)
trailPTS = input(title="Trail Points", type=input.integer, defval=70, step=10)
trailOff = input(title="Trail Offset", type=input.integer, defval=30, step=10)
// Step 6) Submit entry orders
if enterLong
    strategy.entry(id="EL", long=true, qty=posSize)
if enterShort
    strategy.entry(id="ES", long=false, qty=posSize)
if (strategy.position_size > 0)
    strategy.exit(id="XL", from_entry="EL", trail_points = trailPTS, trail_offset = trailOff)
if (strategy.position_size > 0)
    strategy.exit(id="XL1", from_entry="EL", profit = tp, qty_percent = 100, comment = 'Take Profit')
if (strategy.position_size > 0)
    strategy.exit(id="XL2", from_entry="EL", loss = sl, qty_percent = 100, comment = 'Stop Loss')
if (strategy.position_size < 0)
    strategy.exit(id="XS", from_entry="ES", trail_points = trailPTS, trail_offset = trailOff)
if (strategy.position_size < 0)
    strategy.exit(id="XS1", from_entry="EL", profit = tp, qty_percent = 100, comment = 'Take Profit')
if (strategy.position_size < 0)
    strategy.exit(id="XS2", from_entry="EL", loss = sl, qty_percent = 100, comment = 'Stop Loss')
strategy.close_all(when=not tradeWindow)
Expand (82 lines)