Script Name: Buy-Sell Strat
Author: shuby1569
Description: This strategy will produce a buy or sell signal when the following criteria are met:

9 EMA crosses 21 EMA
Recently closed candlestick has 15% higher average volume than previous 5 candles
A candlestick reversal pattern
Price crosses 9 EMA

Feel free to use and modify as you see fit. Happy trading!
PineScript code:

Pine Script™ strategy
Buy/Sell Strat
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
//@version=5
//Author: shuby1569
strategy("Buy/Sell Strat", overlay = true, default_qty_value=100, default_qty_type=strategy.fixed)
fastSourceInput = input(close, "Fast EMA Source")
fastLengthInput = input(9, "Fast EMA Length")
slowSourceInput = input(close, "Slow EMA Source")
slowLengthInput = input(21, "Slow EMA Length")
a = ta.ema(fastSourceInput, fastLengthInput)
b = ta.ema(slowSourceInput, slowLengthInput)
crossUp = ta.crossover(a, b)
crossDown = ta.crossunder(a, b)
close_condition_long = close < a
close_condition_short = close > a
float volAvg = 0
for i = 1 to 5
    volAvg := volAvg + volume[i]
volAvg := volAvg / 5
if (crossUp)
    strategy.entry("long", strategy.long, when = ((volume * 0.85) > volAvg and close > a))
    
if (crossDown)
    strategy.entry("short", strategy.short, when = ((volume * 0.85) > volAvg and close < a))
    
if (close_condition_long)
    strategy.close("long")
if (close_condition_short)
    strategy.close("short")
plot(a, title = "Fast EMA", color = color.green)
plot(b, title = "Slow EMA", color = color.blue)
Expand (36 lines)