Script Name: Daily Crypto Strategy
Author: SoftKill21
Description: This is a long only strategy.

This strategy measures and creates a signal when an asset is moving out of a correlation with CBOE VIX into an inverse correlation.

It also has a risk management with TP/SL based on percentages.


If you have any questions let me know.
PineScript code:

Pine Script™ strategy
Daily Crypto Strategy
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
//@version=4
//@SoftKill21
strategy(title='Daily Crypto Strategy', overlay=true,default_qty_value=100000,default_qty_type= strategy.percent_of_equity,default_qty_value =25, commission_type =strategy.commission.percent, commission_value=0.1)
//take profit and stop loss params
sl_inp = input(7.5, title='Stop Loss %', type=input.float)/100
stop_level = strategy.position_avg_price * (1 - sl_inp)
tp_inp = input(13.0, title='Take Profit %', type=input.float)/100
take_level = strategy.position_avg_price * (1 + tp_inp)
//benchmarks
vix = security('CBOE:VIX', timeframe.period, close)
//correlations coefficients
corVix= correlation(vix,close,20)
signal1 = input(title="signa", type=input.integer, defval=0, minval=-300, maxval=300)
fromDay = input(defval = 1, title = "From Day", minval = 1, maxval = 31)
fromMonth = input(defval = 1, title = "From Month", minval = 1, maxval = 12)
fromYear = input(defval = 2000, title = "From Year", minval = 1970)
 //monday and session 
// To Date Inputs
toDay = input(defval = 31, title = "To Day", minval = 1, maxval = 31)
toMonth = input(defval = 12, title = "To Month", minval = 1, maxval = 12)
toYear = input(defval = 2020, title = "To Year", minval = 1970)
startDate = timestamp(fromYear, fromMonth, fromDay, 00, 00)
finishDate = timestamp(toYear, toMonth, toDay, 00, 00)
time_cond = time >= startDate and time <= finishDate 
if crossunder(corVix, -.2)
    signal1 :=-100
    strategy.entry('buy', strategy.long, when = time_cond)
strategy.exit('Stop Loss/TP',from_entry = 'buy', stop=stop_level, trail_price=take_level)
strategy.exit('Stop Loss/TP',from_entry = 'sell', stop=stop_level, trail_price=take_level)
Expand (47 lines)