Script Name: Gann High Low Strategy omar achbehe
Author: ch0294123
Description: Gann High Low Strategy omar achbehe 
Gann High Low Strategy omar achbehe
PineScript code:

Pine Script™ strategy
Gann High Low Strategy omar achbehe
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
//@version=5
strategy('Gann High Low Strategy', overlay=true)
HPeriod = input(13, 'HIGH Period')
LPeriod = input(21, 'LOW Period')
iff_1 = close < ta.sma(low, LPeriod)[1] ? -1 : 0
HLd = close > ta.sma(high, HPeriod)[1] ? 1 : iff_1
HLv = ta.valuewhen(HLd != 0, HLd, 0)
sma_1 = ta.sma(high, HPeriod)
sma_2 = ta.sma(low, LPeriod)
HiLo = HLv == -1 ? sma_1 : sma_2
HLcolor = HLv == -1 ? color.maroon : color.blue
plot(HiLo, linewidth=2, color=HLcolor)
longCondition = ta.cross(close, HiLo)
shortCondition = ta.crossunder(close, HiLo)
strategy.entry("Long", strategy.long, when=longCondition)
strategy.entry("Short", strategy.short, when=shortCondition)
strategy.close("Long", when=shortCondition)
strategy.close("Short", when=longCondition)
Expand (26 lines)