Script Name: Grospector DCA V.3
Author: GrospectorGraph
Description: This is system for DCA with strategy.

This has 5 zone Extreme high , high , normal , low , Extreme low. You can dynamic set min - max percent every zone.
Extreme zone is derivative short and long which It change Extreme zone to Normal zone all position will be closed.
Every Zone is splitted 10 channel. and this strategy calculate contribution.
and now can predict...
PineScript code:

Pine Script™ strategy
Grospector DCA V.3
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
//@version=5
strategy(title="Grospector DCA V.3", shorttitle="GDCA V.3",precision=7, overlay=true,initial_capital=1000, calc_on_every_tick=true)
//------------------------------ MA ------------------------------
len = input.int(title="MA Period", defval=365*4)
strongLen = input.int(title="Strong Period from MA Period", defval=365)
shortMulti = input.float(title="Short Multi", defval=3)
strongSellMulti = input.float(title="Strong Sell Multi", defval=4)
sellMulti = input.float(title="Sell Multi", defval=2.5)
buyMulti = input.float(title="Buy Multi", defval=1) 
strongBuyMulti = input.float(title="Strong Buy Multi", defval=0.8) 
longMulti = input.float(title="Long Multi", defval=0.3)
price = input.source(title="Price", defval=close)
labelSwitch = input.bool(title='Turn on assistive text', defval=true)
zoneSwitch = input.int(title='Turn on assistive zone',tooltip="1 = all, 2 = chart only, 3 = data only,4 = none", defval=2, options = [1, 2, 3, 4])
predictFuturePrice = input.bool(title='Turn on predict future price', defval=true)
DCA = input.int(title="DCA Plan (USD)",defval=1000)
WaitingDCA = input.float(title="Waiting DCA (USD)",defval=0)
Invested = input.int(title="Invested (USD)",defval=0)
strategySwitch = input.bool(title='Turn on strategy', defval=true)
seperateDayOfMonth = input.int(title='Seperate day of month',tooltip="0 = none, 1-31 day", defval=28,minval=0,maxval=31)
useReserve = input.bool(title='Turn on use reserve', defval=true)
useDerivative = input.bool(title='Turn on use derivative', defval=true)
useHalving = input.bool(title='Turn on use halvings', defval=true)
extendHalfOfHalving = input.int(title='Extend half of halving date', defval=200,minval=0)
StartShortZone = input.int(title="Start Short Zone %",defval=100)
EndShortZone = input.int(title="Start Short Zone %",defval=0,minval=0)
StartSellZone = input.int(title="Start Sell Zone %",defval=100,minval=0,maxval=100)
EndSellZone = input.int(title="End Sell Zone %",defval=0,minval=0,maxval=100)
StartNormalZone = input.int(title="Start Normal Zone %",defval=0,minval=0,maxval=100)
EndNormalZone = input.int(title="End Normal Zone %",defval=100,minval=0,maxval=100)
StartBuyZone = input.int(title="Start Buy Zone %",defval=100,minval=0)
EndBuyZone = input.int(title="End Buy Zone %",defval=200,minval=0)
StartLongZone = input.int(title="Start Long Zone %",defval=0,minval=0)
EndLongZone = input.int(title="End Long Zone %",defval=100,minval=0)
bgcolor(dayofmonth == seperateDayOfMonth ? color.new(color.red, 70) : na,display=seperateDayOfMonth > 0 and seperateDayOfMonth < 32?display.all:display.none)
bar = barstate.isnew
last_bar = barstate.islastconfirmedhistory
//Sell
lenSell = len
srcSell = price
offsetSell = 0
maSell = ta.sma(srcSell*sellMulti, lenSell)
displayZone = zoneSwitch == 1?display.all:zoneSwitch == 2?display.pane:zoneSwitch == 3?display.data_window:zoneSwitch == 4?display.none:display.none
derivertiveDisplayZone = useDerivative ? displayZone:display.none
plot(maSell, color=#f23645, title="Strong Sell", offset=offsetSell, linewidth=3,display=displayZone)
//Strong Sell
offsetStrongSell = 0
maStrongSell = ta.sma(maSell*strongSellMulti, strongLen)
plot(maStrongSell, color=#b22833, title="Sell", offset=offsetStrongSell, linewidth=6,display=displayZone)
//Short
maShort = maStrongSell * shortMulti
plot(maShort, color=#801922, title="Short", linewidth=6,display=derivertiveDisplayZone)
//Buy
lenBuy = len
srcBuy = price
offsetBuy = 0
maBuy = ta.sma(srcBuy*buyMulti, lenBuy)
plot(maBuy, color=color.green, title="Buy", offset=offsetBuy, linewidth=3,display=displayZone)
//Strong Buy
lenStrongBuy = strongLen
offsetStrongBuy = 0
maStrongBuy = ta.sma(maBuy*strongBuyMulti, lenStrongBuy)
plot(maStrongBuy, color=#1b5e20, title="Strong Buy", offset=offsetStrongBuy,linewidth=6,display=displayZone)
//Long
maLong = maStrongBuy * longMulti
plot(maLong, color=#00332a, title="Long", linewidth=6,display=derivertiveDisplayZone)
//index 
indexDerivertive = 0
indexDerivertive := maLong > 0 or maShort > 0 ? indexDerivertive[1]+1 : 0
indexStrong = 0
indexStrong := maStrongBuy > 0 or maStrongSell > 0 ? indexStrong[1]+1 : 0
index = 0
index := maBuy > 0 or maSell > 0 ? index[1]+1 : 0
//channel
higherSell = maSell > maStrongSell ? maSell : maStrongSell
lowerSell = maSell < maStrongSell ? maSell : maStrongSell
higherBuy = maBuy > maStrongBuy ? maBuy : maStrongBuy
lowerBuy = maBuy < maStrongBuy ? maBuy : maStrongBuy
gapShort = (maShort - higherSell)/10
gapSell = (higherSell - lowerSell)/10
gapNormal = (lowerSell - higherBuy)/10
gapBuy = (higherBuy - maStrongBuy)/10
gapLong = (maStrongBuy - maLong)/10
channelShort1 = maShort - (gapShort*1)
channelShort2 = maShort - (gapShort*2)
channelShort3 = maShort - (gapShort*3)
channelShort4 = maShort - (gapShort*4)
channelShort5 = maShort - (gapShort*5)
channelShort6 = maShort - (gapShort*6)
channelShort7 = maShort - (gapShort*7)
channelShort8 = maShort - (gapShort*8)
channelShort9 = maShort - (gapShort*9)
channelShort10 = maShort - (gapShort*10)
plot(channelShort1, color=#801922, title="Strong Short Channel 1", linewidth=1,display=derivertiveDisplayZone)
plot(channelShort2, color=#801922, title="Strong Short Channel 2", linewidth=1,display=derivertiveDisplayZone)
plot(channelShort3, color=#801922, title="Strong Short Channel 3", linewidth=1,display=derivertiveDisplayZone)
plot(channelShort4, color=#801922, title="Strong Short Channel 4", linewidth=1,display=derivertiveDisplayZone)
plot(channelShort5, color=#801922, title="Strong Short Channel 5", linewidth=1,display=derivertiveDisplayZone)
plot(channelShort6, color=#801922, title="Strong Short Channel 6", linewidth=1,display=derivertiveDisplayZone)
plot(channelShort7, color=#801922, title="Strong Short Channel 7", linewidth=1,display=derivertiveDisplayZone)
plot(channelShort8, color=#801922, title="Strong Short Channel 8", linewidth=1,display=derivertiveDisplayZone)
plot(channelShort9, color=#801922, title="Strong Short Channel 9", linewidth=1,display=derivertiveDisplayZone)
plot(channelShort10, color=#801922, title="Strong Short Channel 10", linewidth=1,display=derivertiveDisplayZone)
channelSell1 = higherSell - (gapSell*1)
channelSell2 = higherSell - (gapSell*2)
channelSell3 = higherSell - (gapSell*3)
channelSell4 = higherSell - (gapSell*4)
channelSell5 = higherSell - (gapSell*5)
channelSell6 = higherSell - (gapSell*6)
channelSell7 = higherSell - (gapSell*7)
channelSell8 = higherSell - (gapSell*8)
channelSell9 = higherSell - (gapSell*9)
channelSell10 = higherSell - (gapSell*10)
plot(channelSell1, color=#b22833, title="Strong Sell Channel 1", linewidth=1,display=displayZone)
plot(channelSell2, color=#b22833, title="Strong Sell Channel 2", linewidth=1,display=displayZone)
plot(channelSell3, color=#b22833, title="Strong Sell Channel 3", linewidth=1,display=displayZone)
plot(channelSell4, color=#b22833, title="Strong Sell Channel 4", linewidth=1,display=displayZone)
plot(channelSell5, color=#b22833, title="Strong Sell Channel 5", linewidth=1,display=displayZone)
plot(channelSell6, color=#b22833, title="Strong Sell Channel 6", linewidth=1,display=displayZone)
plot(channelSell7, color=#b22833, title="Strong Sell Channel 7", linewidth=1,display=displayZone)
plot(channelSell8, color=#b22833, title="Strong Sell Channel 8", linewidth=1,display=displayZone)
plot(channelSell9, color=#b22833, title="Strong Sell Channel 9", linewidth=1,display=displayZone)
plot(channelSell10, color=#b22833, title="Strong Sell Channel 10", linewidth=1,display=displayZone)
channelNormal1 = lowerSell - (gapNormal*1) 
channelNormal2 = lowerSell - (gapNormal*2)
channelNormal3 = lowerSell - (gapNormal*3)
channelNormal4 = lowerSell - (gapNormal*4)
channelNormal5 = lowerSell - (gapNormal*5)
channelNormal6 = lowerSell - (gapNormal*6)
channelNormal7 = lowerSell - (gapNormal*7)
channelNormal8 = lowerSell - (gapNormal*8)
channelNormal9 = lowerSell - (gapNormal*9)
channelNormal10 = lowerSell - (gapNormal*10)
plot(channelNormal1, color=#f57f17, title="Normal Channel 1", linewidth=1,display=displayZone)
plot(channelNormal2, color=#f57f17, title="Normal Channel 2", linewidth=1,display=displayZone)
plot(channelNormal3, color=#f57f17, title="Normal Channel 3", linewidth=1,display=displayZone)
plot(channelNormal4, color=#f57f17, title="Normal Channel 4", linewidth=1,display=displayZone)
plot(channelNormal5, color=#f57f17, title="Normal Channel 5", linewidth=1,display=displayZone)
plot(channelNormal6, color=#f57f17, title="Normal Channel 6", linewidth=1,display=displayZone)
plot(channelNormal7, color=#f57f17, title="Normal Channel 7", linewidth=1,display=displayZone)
plot(channelNormal8, color=#f57f17, title="Normal Channel 8", linewidth=1,display=displayZone)
plot(channelNormal9, color=#f57f17, title="Normal Channel 9", linewidth=1,display=displayZone)
plot(channelNormal10, color=#f57f17, title="Normal Channel 10", linewidth=1,display=displayZone)
channelBuy1 = higherBuy - (gapBuy*1)
channelBuy2 = higherBuy - (gapBuy*2)
channelBuy3 = higherBuy - (gapBuy*3)
channelBuy4 = higherBuy - (gapBuy*4)
channelBuy5 = higherBuy - (gapBuy*5)
channelBuy6 = higherBuy - (gapBuy*6)
channelBuy7 = higherBuy - (gapBuy*7)
channelBuy8 = higherBuy - (gapBuy*8)
channelBuy9 = higherBuy - (gapBuy*9)
channelBuy10 = higherBuy - (gapBuy*10)
plot(channelBuy1, color=#1b5e20, title="Strong Buy Channel 1", linewidth=1,display=displayZone)
plot(channelBuy2, color=#1b5e20, title="Strong Buy Channel 2", linewidth=1,display=displayZone)
plot(channelBuy3, color=#1b5e20, title="Strong Buy Channel 3", linewidth=1,display=displayZone)
plot(channelBuy4, color=#1b5e20, title="Strong Buy Channel 4", linewidth=1,display=displayZone)
plot(channelBuy5, color=#1b5e20, title="Strong Buy Channel 5", linewidth=1,display=displayZone)
plot(channelBuy6, color=#1b5e20, title="Strong Buy Channel 6", linewidth=1,display=displayZone)
plot(channelBuy7, color=#1b5e20, title="Strong Buy Channel 7", linewidth=1,display=displayZone)
plot(channelBuy8, color=#1b5e20, title="Strong Buy Channel 8", linewidth=1,display=displayZone)
plot(channelBuy9, color=#1b5e20, title="Strong Buy Channel 9", linewidth=1,display=displayZone)
plot(channelBuy10, color=#1b5e20, title="Strong Buy Channel 10", linewidth=1,display=displayZone)
channelLong1 = maStrongBuy - (gapLong*1)
channelLong2 = maStrongBuy - (gapLong*2)
channelLong3 = maStrongBuy - (gapLong*3)
channelLong4 = maStrongBuy - (gapLong*4)
channelLong5 = maStrongBuy - (gapLong*5)
channelLong6 = maStrongBuy - (gapLong*6)
channelLong7 = maStrongBuy - (gapLong*7)
channelLong8 = maStrongBuy - (gapLong*8)
channelLong9 = maStrongBuy - (gapLong*9)
channelLong10 = maStrongBuy - (gapLong*10)
plot(channelLong1, color=#00332a, title="Strong Long Channel 1", linewidth=1,display=derivertiveDisplayZone)
plot(channelLong2, color=#00332a, title="Strong Long Channel 2", linewidth=1,display=derivertiveDisplayZone)
plot(channelLong3, color=#00332a, title="Strong Long Channel 3", linewidth=1,display=derivertiveDisplayZone)
plot(channelLong4, color=#00332a, title="Strong Long Channel 4", linewidth=1,display=derivertiveDisplayZone)
plot(channelLong5, color=#00332a, title="Strong Long Channel 5", linewidth=1,display=derivertiveDisplayZone)
plot(channelLong6, color=#00332a, title="Strong Long Channel 6", linewidth=1,display=derivertiveDisplayZone)
plot(channelLong7, color=#00332a, title="Strong Long Channel 7", linewidth=1,display=derivertiveDisplayZone)
plot(channelLong8, color=#00332a, title="Strong Long Channel 8", linewidth=1,display=derivertiveDisplayZone)
plot(channelLong9, color=#00332a, title="Strong Long Channel 9", linewidth=1,display=derivertiveDisplayZone)
plot(channelLong10, color=#00332a, title="Strong Long Channel 10", linewidth=1,display=derivertiveDisplayZone)
//---------------------------------------------------------------------------------------------------
//------------------------------------------ Calculate ----------------------------------------------
short = price > higherSell 
sell = price > lowerSell and price < higherSell
halfBuy = price < lowerSell and price > higherBuy 
buy = price < higherBuy and price > lowerBuy
long = price < lowerBuy
percent = 0
percentPeriodOfZoneShort = math.abs(StartShortZone - EndShortZone)/10
percentPeriodOfZoneSell = math.abs(StartSellZone - EndSellZone)/10
percentPeriodOfZoneNormal = math.abs(StartNormalZone - EndNormalZone)/10
percentPeriodOfZoneBuy = math.abs(StartBuyZone - EndBuyZone)/10
percentPeriodOfZoneLong = math.abs(StartLongZone - EndLongZone)/10
if(short)
    percent := price > channelShort1 ? StartShortZone-(percentPeriodOfZoneShort*1) :
              price > channelShort2 ? StartShortZone-(percentPeriodOfZoneShort*2) : 
              price > channelShort3 ? StartShortZone-(percentPeriodOfZoneShort*3) : 
              price > channelShort4 ? StartShortZone-(percentPeriodOfZoneShort*4) : 
              price > channelShort5 ? StartShortZone-(percentPeriodOfZoneShort*5) : 
              price > channelShort6 ? StartShortZone-(percentPeriodOfZoneShort*6) : 
              price > channelShort7 ? StartShortZone-(percentPeriodOfZoneShort*7) : 
              price > channelShort8 ? StartShortZone-(percentPeriodOfZoneShort*8) : 
              price > channelShort9 ? StartShortZone-(percentPeriodOfZoneShort*9) : 
              StartShortZone-(percentPeriodOfZoneShort*10)
else if(sell)
    percent := price > channelSell1 ? StartSellZone-(percentPeriodOfZoneSell*1) :
              price > channelSell2 ? StartSellZone-(percentPeriodOfZoneSell*2) : 
              price > channelSell3 ? StartSellZone-(percentPeriodOfZoneSell*3) : 
              price > channelSell4 ? StartSellZone-(percentPeriodOfZoneSell*4) : 
              price > channelSell5 ? StartSellZone-(percentPeriodOfZoneSell*5) : 
              price > channelSell6 ? StartSellZone-(percentPeriodOfZoneSell*6) : 
              price > channelSell7 ? StartSellZone-(percentPeriodOfZoneSell*7) : 
              price > channelSell8 ? StartSellZone-(percentPeriodOfZoneSell*8) : 
              price > channelSell9 ? StartSellZone-(percentPeriodOfZoneSell*9) : 
              StartSellZone-(percentPeriodOfZoneSell*10)
else if(halfBuy)
    percent := price > channelNormal1 ? StartNormalZone+(percentPeriodOfZoneNormal*1) :
              price > channelNormal2 ? StartNormalZone+(percentPeriodOfZoneNormal*2) : 
              price > channelNormal3 ? StartNormalZone+(percentPeriodOfZoneNormal*3) : 
              price > channelNormal4 ? StartNormalZone+(percentPeriodOfZoneNormal*4) : 
              price > channelNormal5 ? StartNormalZone+(percentPeriodOfZoneNormal*5) : 
              price > channelNormal6 ? StartNormalZone+(percentPeriodOfZoneNormal*6) : 
              price > channelNormal7 ? StartNormalZone+(percentPeriodOfZoneNormal*7) : 
              price > channelNormal8 ? StartNormalZone+(percentPeriodOfZoneNormal*8) : 
              price > channelNormal9 ? StartNormalZone+(percentPeriodOfZoneNormal*9) : 
              StartNormalZone+(percentPeriodOfZoneNormal*10)
else if(buy)
    percent := price > channelBuy1 ? StartBuyZone+(percentPeriodOfZoneBuy*1) :
              price > channelBuy2 ? StartBuyZone+(percentPeriodOfZoneBuy*2) : 
              price > channelBuy3 ? StartBuyZone+(percentPeriodOfZoneBuy*3) : 
              price > channelBuy4 ? StartBuyZone+(percentPeriodOfZoneBuy*4) : 
              price > channelBuy5 ? StartBuyZone+(percentPeriodOfZoneBuy*5) : 
              price > channelBuy6 ? StartBuyZone+(percentPeriodOfZoneBuy*6) : 
              price > channelBuy7 ? StartBuyZone+(percentPeriodOfZoneBuy*7) : 
              price > channelBuy8 ? StartBuyZone+(percentPeriodOfZoneBuy*8) : 
              price > channelBuy9 ? StartBuyZone+(percentPeriodOfZoneBuy*9) :
              StartBuyZone+(percentPeriodOfZoneBuy*10)
else if(long)
    percent := price > channelLong1 ? StartLongZone+(percentPeriodOfZoneLong*1) :
              price > channelLong2 ? StartLongZone+(percentPeriodOfZoneLong*2) : 
              price > channelLong3 ? StartLongZone+(percentPeriodOfZoneLong*3) : 
              price > channelLong4 ? StartLongZone+(percentPeriodOfZoneLong*4) : 
              price > channelLong5 ? StartLongZone+(percentPeriodOfZoneLong*5) : 
              price > channelLong6 ? StartLongZone+(percentPeriodOfZoneLong*6) : 
              price > channelLong7 ? StartLongZone+(percentPeriodOfZoneLong*7) : 
              price > channelLong8 ? StartLongZone+(percentPeriodOfZoneLong*8) : 
              price > channelLong9 ? StartLongZone+(percentPeriodOfZoneLong*9) :
              StartLongZone+(percentPeriodOfZoneLong*10)
//---------------------------------------------------------------------------------------------------
//-------------------------------------------- Display ----------------------------------------------
labeltcolor = color.white
textLabel = buy ? 'Buy' : halfBuy ? "Normal Buy" : long ? "Long" : sell ? "Sell" : "Short"
labelcolor = buy ? color.green : halfBuy ? color.orange : long ? color.green : sell ? color.red : color.red
reserve = 0.0
reserve := barstate.isfirst ? WaitingDCA : reserve[1]
amountBuy = 0.0
amountSell = 0.0
if(percent > 100)
    amountBuy := (useReserve ? (reserve*(percent - 100)/100) : 0) + (DCA*100/100)
else
    amountBuy := (DCA*percent/100)
if(percent < 0)
    amountSell := ((Invested*(percent)/100))/price
else
    amountSell := (Invested*(percent)/100)/price
    
currency = buy ? syminfo.currency : halfBuy ? syminfo.currency : long ? syminfo.currency : sell ? syminfo.basecurrency : syminfo.basecurrency
textAmount = buy or halfBuy or long ? str.format("+{0}",amountBuy) : str.format("-{0}",amountSell)
waitingAmount = amountBuy < DCA ? (DCA - amountBuy) : reserve > amountBuy ? (reserve - amountBuy) : reserve
waitingOperator = percent > 100 ? "" : "+"
textWaitingAmount = buy or halfBuy or long ? str.format("{0}{1}",waitingOperator,waitingAmount) : str.format("-{0}",waitingAmount)
var table panelTable = table.new(position.bottom_right, 5, 5, border_width=1)
f_fillCell(_table, _column, _row, _title, _value, _bgcolor, _txtcolor) =>
    _cellText = _title + " " + _value
    table.cell(_table, _column, _row, _cellText, bgcolor=_bgcolor, text_color=_txtcolor)
var bgPanelColor = color.new(color.black,0)
if labelSwitch
    // Update table
    f_fillCell(panelTable, 0, 0, "Zone:", textLabel, bgPanelColor, labelcolor)
    f_fillCell(panelTable, 0, 1, "Percent:", str.tostring(percent) + " %", bgPanelColor, labelcolor)
    f_fillCell(panelTable, 0, 2, "Amount:", textAmount +" "+ currency, bgPanelColor, labelcolor)
    f_fillCell(panelTable, 0, 3, "Waiting Amount:", textWaitingAmount  +" "+ syminfo.currency, bgPanelColor, color.white)
    f_fillCell(panelTable, 0, 4, "Reserve:", str.tostring(reserve)  +" "+ syminfo.currency, bgPanelColor, color.white)
//---------------------------------------------------------------------------------------------------
//------------------------------------------ Strategy -----------------------------------------------
qty = 0.0
shortSize = 0.0
shortSize := barstate.isfirst ? 0.0:shortSize[1]
longSize = 0.0
longSize := barstate.isfirst ? 0.0:longSize[1]
//Calculate QTY and Waiting DCA
if(buy)
    qty := amountBuy/price
    reserve := percent > 100 and useReserve ? reserve * (percent-100)/100 : reserve + (DCA - amountBuy)
else if(halfBuy)
    qty := amountBuy/price
    reserve := percent > 100 and useReserve ? reserve * (percent-100)/100 : reserve + (DCA - amountBuy)
else if(sell)
    qty := strategy.position_size > 0 ? strategy.position_size * percent/100 : 0
else if(short)
    qty := (DCA/price) * percent/100
else if(long)
    qty := (DCA/price) * percent/100
// plot(reserve,title="reserve",display=display.data_window)
// plot(qty,title="qty",display=display.data_window)
// plot(percent,title="percent",display=display.data_window)
// plot(amountBuy/price,title="amountBuy",display=display.data_window)
// plot(waitingAmount,title="waiting amount",display=display.data_window)
// plot(price,title="price",display=display.data_window)
// plot(indexStrong,title="indexStrong",display=display.data_window)
//Order
if(strategySwitch and qty > 0)
    if(bar and buy)
        strategy.order(str.format("DCA Buy {0}% = {1} {2}",percent,qty,syminfo.basecurrency),strategy.long,qty=qty)
    else if(bar and halfBuy)
        strategy.order(str.format("DCA Normal {0}% = {1} {2}",percent,qty,syminfo.basecurrency),strategy.long,qty=qty)
    else if(bar and sell)
        strategy.order(str.format("DCA Sell {0}% = {1} {2}",percent,qty,syminfo.basecurrency),strategy.short,qty=qty)
        
    if(useDerivative)
        if(bar and short)
            strategy.order(str.format("DCA Short {0}% = {1} {2}",percent,qty,syminfo.basecurrency),strategy.short,qty=qty)
        if(bar and long)
            strategy.order(str.format("DCA Long {0}% = {1} {2}",percent,qty,syminfo.basecurrency),strategy.long,qty=qty)
            
//Exit Derivative
if(strategySwitch and useDerivative)
    if(bar and halfBuy and shortSize > 0)
        strategy.order(str.format("Exit Short",percent,shortSize,syminfo.basecurrency),strategy.long,qty=shortSize)
        shortSize := 0
    if(bar and halfBuy and longSize > 0)
        strategy.order(str.format("Exit Long",percent,longSize,syminfo.basecurrency),strategy.short,qty=longSize)
        longSize := 0
        
//END
if(last_bar)       
    //strategy.close_all()
    if(predictFuturePrice)
        line.new(bar_index-indexStrong, maStrongSell[indexStrong > 0 ? indexStrong-1 : 0], bar_index, maStrongSell , xloc.bar_index, extend.both, #b22833, line.style_dashed, 2)
        line.new(bar_index-index, maSell[index > 0 ? index-1 : 0], bar_index, maSell , xloc.bar_index, extend.both, color.red, line.style_dashed, 2)
        line.new(bar_index-index, maBuy[index > 0 ? index-1 : 0], bar_index, maBuy , xloc.bar_index, extend.both, color.green, line.style_dashed, 2)
        line.new(bar_index-indexStrong, maStrongBuy[indexStrong > 0 ? indexStrong-1 : 0], bar_index, maStrongBuy , xloc.bar_index, extend.both, #1b5e20, line.style_dashed, 2)
        if(useDerivative)
            line.new(bar_index-indexDerivertive, maShort[indexDerivertive > 0 ? indexDerivertive-1 : 0], bar_index, maShort , xloc.bar_index, extend.both, #801922, line.style_dashed, 2)
            line.new(bar_index-indexDerivertive, maLong[indexDerivertive > 0 ? indexDerivertive-1 : 0], bar_index, maLong , xloc.bar_index, extend.both, #00332a, line.style_dashed, 2)
// HALVINGS
DT = 24*60*60*1000
rh1 = timestamp(2012,11,28,0,0)
rh2 = timestamp(2016,7,9,0,0)
rh3 = timestamp(2020,4,30,0,0)
rh4 = timestamp(2024,11,14,0,0) // predict future
rh5 = timestamp(2028,5,3,0,0) // predict future
rh1_range = time >= rh1 - 3*(DT) and time <= rh1 + 3*(DT)
rh2_range = time >= rh2 - 3*(DT) and time <= rh2 + 3*(DT)
rh3_range = time >= rh3 - 3*(DT) and time <= rh3 + 3*(DT)
rh4_range = time >= rh4 - 3*(DT) and time <= rh4 + 3*(DT)
bgcolor(rh1_range and useHalving ? color.red : na)
bgcolor(rh2_range and useHalving ? color.red : na)
bgcolor(rh3_range and useHalving ? color.red : na)
bgcolor(rh4_range and useHalving ? color.red : na)
halfrh_1 = (rh2 + rh1)*0.5 + extendHalfOfHalving*(DT)
halfrh_2 = (rh3 + rh2)*0.5 + extendHalfOfHalving*(DT)
halfrh_3 = (rh4 + rh3)*0.5 + extendHalfOfHalving*(DT)
halfrh_4 = (rh5 + rh4)*0.5 + extendHalfOfHalving*(DT)
halfrh1_range = time >= halfrh_1 - 3*(DT) and time <= halfrh_1 + 3*(DT)
halfrh2_range = time >= halfrh_2 - 3*(DT) and time <= halfrh_2 + 3*(DT)
halfrh3_range = time >= halfrh_3 - 3*(DT) and time <= halfrh_3 + 3*(DT)
halfrh4_range = time >= halfrh_4 - 3*(DT) and time <= halfrh_4 + 3*(DT)
bgcolor(halfrh1_range and useHalving ? color.yellow : na)
bgcolor(halfrh2_range and useHalving ? color.yellow : na)
bgcolor(halfrh3_range and useHalving ? color.yellow : na)
//bgcolor(halfh4_range and useHalving ? color.yellow : na)
Expand (424 lines)