Script Name: Ichimoku Crypto LONG 3h ANY CRYPTO Pair
Author: SoftKill21
Description: This is a strategy which works with most of the crypto pairs on the 3H time frames. 

It beats easily on the long term buy and hold strategy.

This strategy is made from the baseline from ichimoku together with ema 200

This is a long only strategy.


THe condition is : our candle is above ema 200 and our ichimoku its telling we have a long trend. We exit on the...
PineScript code:

Pine Script™ strategy
Ichimoku Crypto LONG 3h ANY CRYPTO Pair
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
//@version=4
//@Author SoftKill21
strategy(title="General Crypto LONG 3h ANY CRYPTO", overlay=true, initial_capital = 1, default_qty_type=strategy.percent_of_equity, default_qty_value=100, commission_type=strategy.commission.percent , commission_value=0.1 )
ema200 = ema(security(heikinashi(syminfo.tickerid), timeframe.period, close), 200)
xversePeriod = 20
basisP = 60
lagPeriod = 120
donchian(len) =>
    avg(lowest(len), highest(len))
conversionLine = donchian(xversePeriod)
baseLine = donchian(basisP)
leadLine1 = avg(conversionLine, baseLine)
leadLine2 = donchian(lagPeriod)
strategy.entry('LONG', strategy.long, when=conversionLine > baseLine and close > ema200)
strategy.close('LONG', when=conversionLine < baseLine)
Expand (24 lines)