Script Name: iMoku (Ichimoku Complete Tool) - The Quant Science
Author: thequantscience
Description: iMoku™ is a professional all-in-one solution for the famous Ichimoku Kinko Hyo indicator. 

The algorithm includes: 

1. Backtesting spot 
2. Visual tool 
3. Auto-trading functions 

With iMoku you can test four different strategies. 

 Strategy 1: Cross Tenkan Sen - Kijun Sen  
A long position is opened with 100% of the invested capital ($1000) when "Tenkan Sen"...
PineScript code:

Pine Script™ strategy
iMoku (Ichimoku Complete Tool) - The Quant Science
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © thequantscience
/////////////////////////////// Design by The Quant Science ™  ////////////////////////////////////
start = 1000
//@version=5
strategy(" iMoku - The Quant Science ™ ", 
             overlay = true, 
             default_qty_type = strategy.percent_of_equity, 
             default_qty_value = 100,
             currency = currency.EUR, 
             initial_capital = start, 
             commission_type = strategy.commission.percent, 
             commission_value = 0.10,
             slippage = 1) 
conversionPeriods = input.int(
         9, 
         minval=1, 
         title="Tenkan Sen Length", 
         group = "Indicator configuration"
         )
basePeriods = input.int(
         26, minval=1, 
         title="Kjun Sen Length", 
         group = "Indicator configuration"
         )
laggingSpan2Periods = input.int(
         52, 
         minval=1, 
         title="Leading Span B Length", 
         group = "Indicator configuration"
         )
displacement = input.int(
         26, minval=1, 
         title="Lagging Span", 
         group = "Indicator configuration"
         )
strategy_1 = input.bool(
         false, 
         title = "Tenkan Sen - Kijun Sen Strategy", 
         group = "Tenkan Sen - Kijun Sen Strategy Configuration"
         )
strategy_2 = input.bool(
         false, 
         title = "Price - Kijun Sen Strategy", 
         group = "Price - Kijun Sen Strategy Configuration"
         )
strategy_3 = input.bool(
         false, 
         title = "Kumo Breakout Strategy", 
         group = "Kumo Breakout Strategy Configuration"
         )
strategy_4 = input.bool(
         false, 
         title = "Kumo Twist Strategy", 
         group = "Kumo Twist Strategy Configuration"
         )
stop_loss = input.float(
         defval = 1, 
         minval = 0.01, 
         step = 0.05, 
         maxval = 500, 
         title = "Stop Loss", 
         group = "Kumo Breakout Strategy Configuration" 
         )
take_profit = input.float(
         defval = 1, 
         minval = 0.01, 
         step = 0.05, 
         maxval = 500, 
         title = "Take Profit", 
         group = "Kumo Breakout Strategy Configuration"
         )
// ########################################################################################################################
// ########################################################################################################################
// ########################################################################################################################
// ########################################################################################################################
// ########################################################################################################################
// ########################################################################################################################
// ########################################################################################################################
donchian(len) => math.avg(
         ta.lowest(
             len
             ), 
             ta.highest(
                 len
                 ))
conversionLine = donchian(
     conversionPeriods
     )
baseLine = donchian(
     basePeriods
     )
leadLine1 = math.avg(
     conversionLine, 
     baseLine
     )
leadLine2 = donchian(
     laggingSpan2Periods
     )
adj_leadLine1 = leadLine1[displacement -1]
adj_leadLine2 = leadLine2[displacement -1]
// 1. Cross Tenkan Sen - Kijun Sen 
price_over_kumo = close > adj_leadLine1
price_under_kumo = close < adj_leadLine2
price_in_kumo = close > adj_leadLine1 
     and close < adj_leadLine2
strong_xover_tenkan_kijun = ta.crossover(
     conversionLine, 
     baseLine
     ) 
     and price_over_kumo
neutro_xover_tenkan_kijun = ta.crossover(
     conversionLine, 
     baseLine
     ) 
     and price_in_kumo
light_xover_tenkan_kijun = ta.crossover(
     conversionLine, 
     baseLine
     ) 
     and price_under_kumo
close_tenkan_kijun = ta.crossunder(
     conversionLine, 
     baseLine
     )
SelectTenkanKijun(type) =>
     switch type 
          "Strong Crossover Tenkan Sen - Kijun Sen" => strong_xover_tenkan_kijun
          "Neutro Crossover Tenkan Sen - Kijun Sen" => neutro_xover_tenkan_kijun
          "Light Crossover Tenkan Sen - Kijun Sen" => light_xover_tenkan_kijun       
type_input = input.string(
     "Strong Crossover Tenkan Sen - Kijun Sen",
     title = "Select strategy: ",
     options = ["Strong Crossover Tenkan Sen - Kijun Sen", "Neutro Crossover Tenkan Sen - Kijun Sen", "Light Crossover Tenkan Sen - Kijun Sen" ],
     tooltip = "",
     group = "Tenkan Sen - Kijun Sen Strategy Configuration"
     )
select_tenkan_kijun = SelectTenkanKijun(
     type_input
     ) 
     and barstate.isconfirmed
price_entry_tenkan_kijun = ta.valuewhen(
     select_tenkan_kijun, 
     close, 
     0
     )
// 2. Cross Price - Kijun Sen 
strong_xover_price_kijun = ta.crossover(
         close, 
         baseLine
         ) 
         and price_over_kumo
neutro_xover_price_kijun  = ta.crossover(
         close, 
         baseLine
         ) 
         and price_in_kumo
light_xover_price_kijun = ta.crossover(
         close, 
         baseLine
         ) 
         and price_under_kumo
close_price_kijun = ta.crossunder(
     close,
     baseLine
     )
SelectPriceKijun(type) =>
     switch type 
          "Strong Crossover Price - Kijun Sen" => strong_xover_price_kijun
          "Neutro Crossover Price - Kijun Sen" => neutro_xover_price_kijun
          "Light Crossover Price - Kijun Sen" => light_xover_price_kijun        
type_input_2 = input.string(
     "Strong Crossover Price - Kijun Sen",
     title = "Select strategy: ",
     options = ["Strong Crossover Price - Kijun Sen", "Neutro Crossover Price - Kijun Sen", "Light Crossover Price - Kijun Sen" ],
     tooltip = "",
     group = "Price - Kijun Sen Strategy Configuration"
     )
select_price_kijun = SelectPriceKijun(
     type_input_2
     ) 
     and barstate.isconfirmed
price_entry_price_kijun = ta.valuewhen(
     select_price_kijun, 
     close, 
     0
     )
// 3. Kumo breakout 
kumo_breakout = ta.crossover(
     close, 
     adj_leadLine1
     ) 
// 4. Kumo Twist 
strong_kumo_twist = ta.crossover(
     adj_leadLine1, 
     adj_leadLine2
     ) 
     and price_over_kumo
light_kumo_twist = ta.crossover(
     adj_leadLine1, 
     adj_leadLine2
     ) 
     and price_under_kumo
close_kumo_twist = ta.crossunder(
     adj_leadLine1, 
     adj_leadLine2)
SelectKumoTwist(type) =>
     switch type 
          "Strong Crossover Kumo Twist" => strong_kumo_twist
          "Light Crossover Kumo Twist" => light_kumo_twist       
type_input_3 = input.string(
     "Strong Crossover Kumo Twist",
     title = "Select strategy: ",
     options = ["Strong Crossover Kumo Twist", "Light Crossover Kumo Twist" ],
     tooltip = "",
     group = "Kumo Twist Strategy Configuration"
     )
select_kumo_twist = SelectKumoTwist(
     type_input_3
     ) 
     and barstate.isconfirmed
price_entry_kumo_twist = ta.valuewhen(
     select_kumo_twist, 
     close, 
     0
     )
// ########################################################################################################################
var tb = table.new(
     position.bottom_left, 
     1, 1, 
     bgcolor = color.new(
         color.blue, 
         90
         ))
if barstate.isfirst
    table.cell(
      tb, 
      0, 0, 
      'Developed by The Quant Science™'
      ,text_size = size.normal
      ,text_color = color.new(
           color.blue, 
           20
           ))
// ########################################################################################################################
// ########################################################################################################################
// ########################################################################################################################
// ########################################################################################################################
// ########################################################################################################################
// ########################################################################################################################
entry_string_1 = input.string(
     title = "Entry string:", 
     defval = "#######", 
     confirm = false, 
     group = "Tenkan Sen - Kijun Sen Strategy Configuration",
     tooltip = "Enter 3Commas or Cryptohopper string link. Enter only the open entry link in this field."
     )
exit_string_1 = input.string(
     title = "Exit string:", 
     defval = "#######", 
     confirm = false, 
     group = "Tenkan Sen - Kijun Sen Strategy Configuration",
     tooltip = "Enter 3Commas or Cryptohopper string link. Enter only the close exit link in this field."
     )
isLong  = false
isLong := nz(
     isLong[1], 
     false
     )
isSellLong  = false
isSellLong := nz(
     isSellLong[1], 
     false
     )
LONG = not isLong and select_tenkan_kijun
price_1 = ta.valuewhen(
     LONG, 
     close, 
     0
     )
lot_1 = start / price_1
CLOSE_LONG = not isSellLong and close_tenkan_kijun
if (LONG) and strategy_1 == true 
     isLong := true
     isSellLong := false
    strategy.entry(
         id = "Tenkan Kijun Open", 
         direction = strategy.long, 
         qty = lot_1, 
         limit = price_entry_tenkan_kijun
         )
    alert(
         entry_string_1, 
         alert.freq_once_per_bar
         )
          
if (CLOSE_LONG) and strategy_1 == true 
     isLong := false
     isSellLong := true
    strategy.close_all(
         comment = "Tenkan Kijun Closing"
         )
    alert(
         exit_string_1, 
         alert.freq_once_per_bar
         )
// ########################################################################################################################
entry_string_2 = input.string(
     title = "Entry string:", 
     defval = "#######", 
     confirm = false, 
     group = "Price - Kijun Sen Strategy Configuration",
     tooltip = "Enter 3Commas or Cryptohopper string link. Enter only the open entry link in this field."
     )
exit_string_2 = input.string(
     title = "Exit string:", 
     defval = "#######", 
     confirm = false, 
     group = "Price - Kijun Sen Strategy Configuration",
     tooltip = "Enter 3Commas or Cryptohopper string link. Enter only the close exit link in this field."
     )
isLong_2  = false
isLong_2 := nz(
     isLong_2[1], 
     false
     )
isSellLong_2 = false
isSellLong_2 := nz(
     isSellLong_2[1], 
     false
     )
LONG_2 = not isLong_2 and select_price_kijun
price_2 = ta.valuewhen(
     LONG_2, 
     close, 
     0
     )
lot_2 = start / price_2
CLOSE_LONG_2 = not isSellLong_2 and close_price_kijun
if (LONG_2) and strategy_2 == true 
     isLong_2 := true
     isSellLong_2 := false
    strategy.entry(
         id = "Price Kijun Open", 
         direction = strategy.long, 
         qty = lot_2, 
         limit = price_entry_price_kijun
         )
    alert(
         entry_string_2, 
         alert.freq_once_per_bar
         )
if (CLOSE_LONG_2) and strategy_2 == true 
     isLong_2 := false
     isSellLong_2 := true
    strategy.close_all(comment = "Price Kijun Closing")
    alert(
         exit_string_2, 
         alert.freq_once_per_bar
         )
// ########################################################################################################################
entry_string_3 = input.string(
     title = "Entry string:", 
     defval = "#######", 
     confirm = false, 
     group = "Kumo Breakout Strategy Configuration",
     tooltip = "Enter 3Commas or Cryptohopper string link. Enter only the open entry link in this field."
     )
exit_string_3 = input.string(
     title = "Exit string:", 
     defval = "#######", 
     confirm = false, 
     group = "Kumo Breakout Strategy Configuration",
     tooltip = "Enter 3Commas or Cryptohopper string link. Enter only the close exit link in this field."
     )
isLong_3  = false
isLong_3 := nz(
     isLong_3[1], 
     false
     )
isSellLong_3  = false
isSellLong_3 := nz(
     isSellLong_3[1], 
     false 
     )
LONG_3 = not isLong_3 and kumo_breakout 
price_kumobrk = ta.valuewhen(
     LONG_3, 
     close, 
     0
     )
lot_3 = start / price_kumobrk
take_profit_kumobrk_price = (
     price_kumobrk * (
          100 + 
          take_profit
          ) / 100
          )
stop_loss_kumobrk_price = (
     price_kumobrk * (
         100 - 
         stop_loss
         ) / 100
         )
if (LONG_3) and strategy_3 == true 
     isLong_3 := true
     isSellLong_3 := false
    strategy.entry(
         id = "Kumo Breakout Open", 
         direction = strategy.long, 
         qty = lot_3, 
         limit = price_kumobrk
         )
    alert(
         entry_string_3, 
         alert.freq_once_per_bar
         )
if (take_profit_kumobrk_price) 
     isLong_3 := false
     isSellLong_3 := true
    strategy.exit(
         id = "Kumo Breakout Closing", 
         from_entry = "Kumo Breakout Open", 
         limit = take_profit_kumobrk_price, 
         stop = stop_loss_kumobrk_price
         )
    alert(
         exit_string_3, 
         alert.freq_once_per_bar
         )
if (stop_loss_kumobrk_price) 
     isLong_3 := false
     isSellLong_3 := true
    strategy.exit(
         id = "Kumo Breakout Closing", 
         from_entry = "Kumo Breakout Open", 
         limit = take_profit_kumobrk_price, 
         stop = stop_loss_kumobrk_price
         )
    alert(
         exit_string_3, 
         alert.freq_once_per_bar
         )
// ########################################################################################################################
entry_string_4 = input.string(
     title = "Entry string:", 
     defval = "#######", 
     confirm = false, 
     group = "Kumo Twist Strategy Configuration",
     tooltip = "Enter 3Commas or Cryptohopper string link. Enter only the open entry link in this field."
     )
exit_string_4 = input.string(
     title = "Exit string:", 
     defval = "#######", 
     confirm = false, 
     group = "Kumo Twist Strategy Configuration",
     tooltip = "Enter 3Commas or Cryptohopper string link. Enter only the close exit link in this field."
     )
isLong_4  = false
isLong_4 := nz(
     isLong_4[1], 
     false
     )
isSellLong_4  = false
isSellLong_4 := nz(
     isSellLong_4[1], 
     false
     )
LONG_4 = not isLong_4 and select_kumo_twist
price_4 = ta.valuewhen(
     LONG_4, 
     close, 
     0
     )
lot_4 = start / price_4
CLOSE_LONG_4 = not isSellLong_4 and close_kumo_twist
if (LONG_4) and strategy_4 == true 
     isLong_4 := true
     isSellLong_4 := false
    strategy.entry(
         id = "Kumo Twist Open", 
         direction = strategy.long, 
         qty = lot_4, 
         limit = price_entry_kumo_twist
         )
    alert(
         entry_string_4, 
         alert.freq_once_per_bar
         )
if (CLOSE_LONG_4) and strategy_4 == true 
     isLong_4 := false
     isSellLong_4 := true
    strategy.close_all(comment = "Kumo Twist Closing")
    alert(
         exit_string_4, 
         alert.freq_once_per_bar
         )
// ########################################################################################################################
// ########################################################################################################################
// ########################################################################################################################
// ########################################################################################################################
// ########################################################################################################################
plot(
     conversionLine, 
     color =color.new(
          color.aqua, 
          65), 
          title = "Conversion Line or Tenkan Sen"
          )
plot(
     baseLine, 
     color=color.new(
         color.purple, 
         65), 
         title="Base Line or Kijun Sen"
         )
plot(
     close, 
     offset = -displacement + 1, 
     color= color.new(
         color.gray, 
         85
         ), 
         title="Lagging Span Chokou"
         )
p1 = plot(
     leadLine1, 
     offset = displacement - 1, 
     color= color.aqua,
      title="Leading Span A"
     )
p2 = plot(
     leadLine2, 
     offset = displacement - 1, 
     color= color.aqua,
      title="Leading Span B"
     )
fill(
     p1, 
     p2, 
     color = leadLine1 > leadLine2 ? color.rgb(
         21, 149, 253, 90
         ) : color.rgb(
             21, 149, 253, 90
             ))
// ########################################################################################################################
// ########################################################################################################################
// ########################################################################################################################
// ########################################################################################################################
// ########################################################################################################################
Expand (639 lines)