Script Name: MACD Cross+MA
Author: DeMindSET
Description: Strategy MACD cross + Ma cross
การเข้าจะเข้าต่อเมื่อมีการ Cross ของ MACD ก่อน แล้วมีการ Cross ของเส้น ma 9,26 ตามมา
จากการ Backtest ของผมถือว่าเป้น Indicator ที่ค่อนข้างบอกให้เข้าช้าเลยทีเดียว แต่ใช้ Follow เทรนพอใช้ได้อยู่ครับ
แนะนำให้ใช้ในช่วงที่ตลาดเป็นขาขึ้นนะครับ ช่วงหมียาวอย่างปี 2018 Indicator ตั้วนี้ไม่เวิร์คอย่างแรงเลยครับ
ในภาพ backtest ตั้งแต่ปี 2019 -...
PineScript code:

Pine Script™ strategy
MACD Cross+MA
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
//@version=4
strategy("MACD Cross+MA", overlay=true)
//@version=4
// Getting inputs MACD
fast_length = input(title="MACDFast Length", type=input.integer, defval=12)
slow_length = input(title="MACDSlow Length", type=input.integer, defval=26)
src = input(title="MACDSource", type=input.source, defval=close)
signal_length = input(title="MACDSignal Smoothing", type=input.integer, minval = 1, maxval = 50, defval = 9)
sma_source = input(title="MACDSimple MA(Oscillator)", type=input.bool, defval=false)
sma_signal = input(title="MACDSimple MA(Signal Line)", type=input.bool, defval=false)
// Calculating MACD
fast_ma = sma_source ? sma(src, fast_length) : ema(src, fast_length)
slow_ma = sma_source ? sma(src, slow_length) : ema(src, slow_length)
macd = fast_ma - slow_ma
signal = sma_signal ? sma(macd, signal_length) : ema(macd, signal_length)
hist = macd - signal
// Input SMA1
FastMA= input(9, minval=1 , title="FastMA")
SlowMA= input(26, minval=1 , title="SlowMA")
// === INPUT BACKTEST RANGE ===
FromYear  = input(defval = 2019, title = "From Year", minval = 2009)
FromMonth = input(defval = 1, title = "From Month", minval = 1, maxval = 12)
FromDay   = input(defval = 1, title = "From Day", minval = 1, maxval = 31)
ToYear    = input(defval = 9999, title = "To Year", minval = 2009)
ToMonth   = input(defval = 12, title = "To Month", minval = 1, maxval = 12)
ToDay     = input(defval = 31, title = "To Day", minval = 1, maxval = 31)
// === FUNCTION EXAMPLE ===
start     = timestamp(FromYear, FromMonth, FromDay, 00, 00)  // backtest start window
finish    = timestamp(ToYear, ToMonth, ToDay, 23, 59)        // backtest finish window
window()  => time >= start and time <= finish ? true : false // create function "within window of time"
//plot
Slow=sma(close,SlowMA)
Fast=sma(close,FastMA)
plot(Slow,color=color.green)
plot(Fast,color=color.red)
plot(cross(Fast,Slow)?Fast:na,style=plot.style_cross,linewidth=4)
//Condition
BMacdcondition= (macd>signal)
SMacdcondition= (macd<signal)
longCondition = crossover(sma(close, FastMA), sma(close,SlowMA))
shortCondition = crossunder(sma(close,FastMA), sma(close,SlowMA))
//entry
if (BMacdcondition) and window()
    strategy.entry("LONG", strategy.long,when=(longCondition))
if (shortCondition) and window()
    strategy.close("LONG", qty_percent=100 , comment="TP",when=(SMacdcondition))
Expand (52 lines)