Script Name: MACD Moon Strat
Author: ldavi1997
Description: Hey john this is for you bby
PineScript code:

Pine Script™ strategy
MACD Moon Strat
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
//@version=4
////////////////////////////////////////////////////////////////////////////////
// BACKTESTING RANGE
 
// From Date Inputs
fromDay = input(defval = 1, title = "From Day", minval = 1, maxval = 31)
fromMonth = input(defval = 1, title = "From Month", minval = 1, maxval = 12)
fromYear = input(defval = 2020, title = "From Year", minval = 1970)
 
// To Date Inputs
toDay = input(defval = 1, title = "To Day", minval = 1, maxval = 31)
toMonth = input(defval = 1, title = "To Month", minval = 1, maxval = 12)
toYear = input(defval = 2021, title = "To Year", minval = 1970)
 
// Calculate start/end date and time condition
startDate = timestamp(fromYear, fromMonth, fromDay, 00, 00)
finishDate = timestamp(toYear, toMonth, toDay, 00, 00)
time_cond = time >= startDate and time <= finishDate
 
////////////////////////////////////////////////////////////////////////////////
strategy("MACD Strategy", overlay=true, initial_capital=10000, default_qty_value=100, default_qty_type=strategy.percent_of_equity, commission_type=strategy.commission.cash_per_order,
 commission_value=9.50)
fastLength = input(12)
slowlength = input(26)
MACDLength = input(9)
MACD = ema(close, fastLength) - ema(close, slowlength)
aMACD = ema(MACD, MACDLength)
delta = MACD - aMACD
 
  
strategy.risk.allow_entry_in(strategy.direction.long)
if (crossover(delta, 0)) and (close>1.1*ema(close,200)) and MACD<0 and time_cond 
    strategy.entry("MacdLE", strategy.long, comment="Buy")
if (high<ema(close,8)) or (low<ema(close,100)) and time_cond
    strategy.entry("MacdSE", strategy.short, comment="Sell")
if (not time_cond)
    strategy.close_all()
    
    
Expand (47 lines)