Script Name: Mayer Multiple Strategy
Author: xtradernet
Description: Created by Trace Mayer, the Mayer Multiple is calculated dividing the current price of Bitcoin by its 200-day moving average. This simple script allows to backtest strategies based on Mayer Multiple levels, which can be easily adjusted. It can be tested on any chart and any timeframe.
PineScript code:

Pine Script™ strategy
Mayer Multiple Strategy
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © xtradernet
//@version=4
// Quick script to backtest a strategy based on Mayer Multiple
strategy("Mayer Multiple Strategy", shorttitle="Mayer_Crypto", overlay=true)
length = input(200, type=input.integer, title="Price SMA Length")
threshold = input(1.48, step=.1, type=input.float, title="Threshold")
exit = input(1.70, step=.1, type=input.float, title="Exit Level")
// Bitcoin price / 200 day moving average value = Mayer Multiple
ma = sma(close, length)
multiple = close / ma
if (crossunder(threshold,multiple))
    strategy.entry("Long", strategy.long, comment="MayerLong")
strategy.close("Long", when=crossover(multiple,exit), comment="MayerClose")
Expand (24 lines)