Script Name: OBV MA Strategy
Author: sonnyparlin
Description: The On Balance Volume + Moving Average Strategy 

Parameters: 1H candles, ETHUSDT on BINANCEUS, commission percent uses Binance's maker/taker fees of 0.075%
Strategy: I create a 30 day moving average of the On Balance Volume "obvSma = ta.sma(ta.obv, 30)." Then I use the following buy conditions:

 
  OBV crosses above the OBV moving average
  The obv drops x%...
PineScript code:

Pine Script™ strategy
OBV MA Strategy
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © sonnyparlin
//@version=5
strategy("OBV Strategy V2", overlay=true, 
     commission_type=strategy.commission.percent, 
     currency=currency.USD, 
     commission_value=0.075,
     slippage=2, initial_capital=10000)
plot(close)
// Removed script
Expand (13 lines)