Script Name: Repaint Demonstration in Security Function Call using Higher TF
Author: akrit8888
Description: Many Coders mistakenly use Security Function call on their backtest without knowing that the security function does look forward in the future and provide an unrealistic repainted result.
This Script's purpose is to give out a clear demonstration of how the security function does look forward in the data and should NOT be used by any means as a real trading...
PineScript code:

Pine Script™ strategy
Repaint Demonstration in Security Function Call using Higher TF
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © akrit8888
// @version=4
// "This Script is for demonstration of repaint by using security function to lookup the Future" 
// "And should NOT by any means be use in as a real trading strategy."
strategy("Repaint Demonstration in Security Function Call using Higher TF", overlay=true, default_qty_type=strategy.percent_of_equity, default_qty_value=100)
bigTF = input("W", "Future Sight: ", input.resolution)
bigTFClose = security(syminfo.tickerid, bigTF, close)
buy = crossover(close, bigTFClose)
sell = crossover(bigTFClose, close)
plot(close)
plot(bigTFClose)
strategy.entry("L", true, when = buy)
strategy.close("L", when = sell)
Expand (20 lines)