Script Name: robotrading ZeroCCI
Author: ROBO_Trading
Description: It was not me who authored the strategy. I do not know who the real author of this strategy is. I read about it on wikipedia :) And decided to test the strategy on the cryptocurrency market. It turned out that this strategy really works. The strategy is very simple.

 Indicator 

CCI indicator with default settings is used. The settings can be changed. Nothing...
PineScript code:

Pine Script™ strategy
robotrading ZeroCCI
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
//@version=5
strategy(title="robotrading ZeroCCI", shorttitle="ZeroCCI", default_qty_type = strategy.percent_of_equity, default_qty_value = 100, pyramiding = 0, commission_value = 0.1)
length = input.int(20, minval=1)
src = input(hlc3, title="Source")
ma = ta.sma(src, length)
cci = (src - ma) / (0.015 * ta.dev(src, length))
plot(cci, "CCI", color=#2962FF)
band1 = hline(100, "Upper Band", color=#787B86, linestyle=hline.style_dashed)
band0 = hline(-100, "Lower Band", color=#787B86, linestyle=hline.style_dashed)
fill(band1, band0, color=color.rgb(33, 150, 243, 90), title="Background")
plot(0, color = color.black)
if cci > 0
    strategy.entry("Long", strategy.long)
if cci < 0
    strategy.entry("Short", strategy.short)
Expand (16 lines)