Script Name: robotrading body
Author: ROBO_Trading
Description: This is a very simple and universal strategy. Good for crypto. For BTC/USD, shitcoin/BTC.

 Strategy 

Long positions only. If the candle is falling and the candle body is 3 or more times the average candle body, then open a long position.
If the candle is rising, we should close a long position.
Short positions are not used.
This is a counter-trend strategy.
The...
PineScript code:

Pine Script™ strategy
robotrading body
Copy code
1
2
3
4
5
6
7
8
//@version=4
strategy("robotrading body", shorttitle = "body", overlay = true, default_qty_type = strategy.percent_of_equity, default_qty_value = 100, commission_value = 0.1)
mult = input(3.0)
body = abs(close - open)
if close < open and body > sma(body, 100) * mult
    strategy.entry("L", strategy.long)
if close > open
    strategy.close_all()