Script Name: RSI Centered Pivots
Author: OztheWoz
Description: Just a simple RSI central pivot strategy I made for a friend.
Backtested on BYBIT:BTCUSD, 155m.

 DISCLAIMER : Please do your own research into anything you use before using it to trade.
PineScript code:

Pine Script™ strategy
RSI Centered Pivots
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © OztheWoz
//@version=4
strategy("RSI Fractals", initial_capital=10000, commission_type=strategy.commission.percent, commission_value=0.1, slippage=3)
// study("RSI Fractals")
len = input(19, "Length")
rsi = rsi(close, len)
fractup = pivotlow(rsi, 2, 2)
fractdn = pivothigh(rsi, 2, 2)
plot(rsi)
hline(80, color=color.gray)
hline(20, color=color.gray)
plotshape(fractup, style=shape.triangleup, location=location.bottom, color=color.green, offset=-2)
strategy.entry("Long", true, 1, when=fractup)
strategy.close("Long", when=(rsi >= 80))
stoploss = close[1] - (close[1] * 0.5/100)
strategy.exit("Long", "Exit Long", stop=stoploss)
// alertcondition(fractup, "RSI Fractal Up",   "RSI Fractal V \nExpect Reversal Bearish")
// alertcondition(fractdn, "RSI Fractal Down", "RSI Fractal ^ \nExpect Reversal Bullish")
// alertcondition((rsi >= 80), "RSI Overbought",  "RSI Overbought \nSell Before Bearish Reversal")
// alertcondition((rsi <= 20), "RSI Underbought", "RSI Underbought \nSell Before Bullish Reversal")
Expand (27 lines)