Script Name: Supertrend TEST Strategy
Author: yanaVprofit
Description: супер тренд ааааааываыв вдрплввр арапр ыапап опвоапо
PineScript code:

Pine Script™ strategy
Supertrend TEST Strategy
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
//@version=5
strategy("RSI Strategy", overlay=true)
length = input( 14 )
overSold = input( 30 )
overBought = input( 70 )
price = close
vrsi = ta.rsi(price, length)
co = ta.crossover(vrsi, overSold)
cu = ta.crossunder(vrsi, overBought)
if (not na(vrsi))
    if (co)
        strategy.entry("RsiLE", strategy.long, comment="RsiLE")
    if (cu)
        strategy.entry("RsiSE", strategy.short, comment="RsiSE")
//plot(strategy.equity, title="equity", color=color.red, linewidth=2, style=plot.style_areabr)
Expand (15 lines)