Script Name: TRAX Detrended Price Strategy
Author: DraftVenture
Description: In this script, the "TRAX" (TRIX) indicator is calculated using the Volume Weighted Moving Average (VWMA) instead of Exponential Moving Average (EMA) like the standard TRIX. The Detrended Price is used to identify short term cycles with a rate of change verses the rate of change from a triple smoothed TRAX VWMA . The strategy is intended for counter-trend trading,...
PineScript code:

Pine Script™ strategy
TRAX Detrended Price Strategy
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © DraftVenture
//@version=5
strategy("TRAX DPO", overlay=true)
// TRAX Calculation
traxlength = input.int(12, title = "TRAX Length", minval=1)
trax = 10000 * ta.change(ta.vwma(ta.vwma(ta.vwma(math.log(close), traxlength), traxlength), traxlength))
// DPO Calculation
period_ = input.int(19, title="DPO Length", minval=1)
barsback = period_/2 + 1
ma = ta.sma(close, period_)
dpo = close[barsback] - ma
// MA Confirmation Calculation
len = input.int(3, minval=1, title="SMA Confirmation Length")
src = input(close, title="SMA Source")
offset = input.int(title="Offset", defval=0, minval=-500, maxval=500)
out = ta.sma(src, len)
plot(out, color=color.white, title="MA", offset=offset)
// DPO-TRAX Oscillator
dpotrax = dpo - trax
plot(dpotrax, color=color.blue, title="DPO-TRAX Oscillator", offset=offset)
// Crossover Conditions
longCondition = ta.crossover(dpo, trax) and trax < 0 and close > out
shortCondition = ta.crossunder(dpo, trax) and trax > 0 and close < out
// Strategy Logic
if (longCondition)
    strategy.entry("Long", strategy.long)
if (shortCondition)
    strategy.entry("Short", strategy.short)
// Highlight periods of zero-line crossover
bgcolor(longCondition ? color.new(color.green, 80) : na)
bgcolor(shortCondition ? color.new(color.red, 80) : na)
// Strategy by KP
Expand (42 lines)