Script Name: Triple RSI strategy
Author: Trade_by_DB
Description: This strategy is commonly used both in forex and stock markets for reversal trading. when the rsi line reaches and crosses simultaneously at 3 rsi setups i.e at 7, 14, and 21, a signal is generated.

This strategy works best in 1-hour timeframe. It provides over 60 to 80 percent accuracy in 1-hour timeframe.

In the stock market, this strategy provides an...
PineScript code:

Pine Script™ strategy
Triple RSI strategy
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Trade_by_DB
//@version=5
strategy("3 RSI", overlay=true, margin_long=100, margin_short=100)
// 3 rsi strategy , when all of them are overbought we sell, and vice versa
rsi7 = ta.rsi(close,7)
rsi14 = ta.rsi(close,14)
rsi21 = ta.rsi(close,21)
// sell condition
sell = ta.crossunder(rsi7,70) and ta.crossunder(rsi14,70) and ta.crossunder(rsi21,70)
//buy condition
buy = ta.crossover(rsi7,30) and ta.crossover(rsi14,30) and ta.crossover(rsi21,30)
if (buy)
    strategy.entry("BUY", strategy.long)
if (sell)
    strategy.entry("SELL", strategy.short)
Expand (26 lines)