Script Name: VIX Futures Spread Strategy
Author: jtonka
Description: This script was an exercise in learning Pinescript and exploring the futures curve of the VIX in relation to SPY. Was deleted by TV, trying to republish it now with updated parameters for slippage and commission and a more detailed description.

"VIX Futures Spread Strategy" is a trading strategy that capitalizes on the spread between the 3-month VIX futures...
PineScript code:

Pine Script™ strategy
VIX Futures Spread Strategy
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
//@version=4
strategy("VIX Futures Spread Strategy", overlay=false, pyramiding=10, initial_capital=10000, commission_type=strategy.commission.percent, commission_value=0.005, slippage = 2)
spr = security("CBOE:VIX3M", "W", hl2) - security("TVC:VIX", "W", hl2)
plot(spr, title="VIX 3M - VIX", color=color.gray, style=plot.style_columns, linewidth=2, transp=30)
h2 = hline(0, color=color.green)
h3 = hline(3, color=color.red)
// This strategy buys when the VIX futures spread is negative
// It sells when the VIX futures spread is above 3, but only sells to close a position
vixSpread = spr
// Entry rules
longCondition = (vixSpread < 0) and (year > 2018) and (barstate.isconfirmed)
if longCondition
    strategy.entry("Long", strategy.long, qty=10)
// Exit rules
shortCondition = (vixSpread > 3) and strategy.position_size > 0
if shortCondition
    strategy.close("Long")
Expand (25 lines)