Script Name: Aggregate BTC Volume + EMA Strat
Author: tweakerID
Description: // This strategy buys when the price crosses the Fast EMA. It can go long only 
// when the price is above the slow EMA and short when is below. The exit 
// is determined by volume spikes, when the volume is greater than the Volume
// MA multiplied by the assigned input multiplier. Thanks to MartinShkreli 
// for the Aggregated BTC volume. There is also a Maximum...
PineScript code:

Pine Script™ strategy
Aggregate BTC Volume + EMA Strat
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
//@license=MIT
// © MartinShkreli and tweakerID
// This strategy buys when the price crosses the Fast EMA. It can go long only 
// when the price is above the slow EMA and short when is below. The exit 
// is determined by volume spikes, when the volume is greater than the Volume
// MA multiplied by the assigned input multiplier. Thanks to MartinShkreli 
// for the Aggregated BTC volume. There is also a Maximum Loss filter which 
// should be modified depending on the traded market.
//@version=4
strategy("Aggregate BTC Volume + EMA Strat", shorttitle="BTC Vol + EMA Strat", overlay=false, default_qty_type=strategy.percent_of_equity, default_qty_value=100, initial_capital=10000, commission_value=0.04, calc_on_every_tick=false, slippage=0)
direction = input(0, title = "Direction (Long=1, Both=0, Short=-1 ", type=input.integer, minval=-1, maxval=1)
strategy.risk.allow_entry_in(direction == 0 ? strategy.direction.all : (direction < 0 ? strategy.direction.short : strategy.direction.long))
res = timeframe.period
getVolumeSym(symbolPair) => security(symbolPair, res, volume)
getVolumeSymNz(symbolPair) => nz(getVolumeSym(symbolPair))
showma  = input(title="Show MA", type=input.bool, defval=true)
i_MAslow = input(100, title="Vol Slow MA Length")
i_MAfast = input(10, title="Vol Fast MA Length")
i_EMA = input(255, title="Slow EMA Length")
i_EMAFast = input(40, title="Fast EMA Length")
i_VolMult = input(4, step=.2, title="Volume MA Multiplier")
i_useMAFast = input(true, title="Use Fast MA for exit condition")
i_reverse = input(false, title="Reverse Trades")
i_AllowMaxLoss = input(true, title="Allow Maximum Loss Filter")
i_MaxLoss = input(6, title="Maximum Loss % Allowed Per Day")
//Aggregated Volume
vol = 0*volume
vol := vol + getVolumeSymNz("BINANCE:BTCUSDT")
vol := vol + getVolumeSymNz("BINANCE:BTCUSDTPERP")
vol := vol + getVolumeSymNz("OKEX:BTCUSDT")
vol := vol + getVolumeSymNz("OKEX:BTCUSDTPERP")
vol := vol + getVolumeSymNz("HUOBI:BTCUSDT")
vol := vol + getVolumeSymNz("HUOBI:BTCPERP")
vol := vol + getVolumeSymNz("FTX:BTCUSD")
vol := vol + getVolumeSymNz("FTX:BTCPERP")
vol := vol + getVolumeSymNz("KRAKEN:XBTUSD")
vol := vol + getVolumeSymNz("KRAKEN:XBTUSDPERP")
vol := vol + getVolumeSymNz("COINBASE:BTCUSD")
vol := vol + getVolumeSymNz("DERIBIT:BTCPERP")
vol := vol + getVolumeSymNz("BITFINEX:BTCUSD")
vol := vol + getVolumeSymNz("BITMEX:XBTUSD")
vol := vol + getVolumeSymNz("BITSTAMP:BTCUSD") 
vol := vol + getVolumeSymNz("BYBIT:BTCUSD") 
//Strategy Variables
strategy.risk.max_intraday_loss(i_AllowMaxLoss ? i_MaxLoss : 100, strategy.percent_of_equity)
EMA=ema(close, i_EMA)
EMAFast=ema(close, i_EMAFast)
MASlow=sma(vol, i_MAslow)
MAFast=sma(vol, i_MAfast)
//Trading Logic
BUY=crossover(close, EMAFast) and close > EMA
SELL=crossunder(close, EMAFast) and close < EMA
Exit=vol > (i_useMAFast ? MAFast*i_VolMult : MASlow*i_VolMult) 
MAExit = strategy.position_size < 0 ? crossover(close, EMA) : 
 strategy.position_size > 0 ? crossunder(close, EMA) : na
//Entries
strategy.entry("long", i_reverse?false:true, when=BUY)
strategy.entry("short", i_reverse?true:false, when=SELL)
strategy.close_all(when=Exit)
//Plots
plot(vol, "Volume", color=(open > close) ? #B03838 : #008060, style=plot.style_columns)
plot(showma ? MASlow : na, color=color.yellow)
plot(showma ? MAFast : na)
Expand (76 lines)