Script Name: Binary Options Strategy Template
Author: Honestcowboy
Description: With the hype around Binary Options trading (more like gambling instead of trading) it is good to be able to backtest a strategy before using it in the live markets. 
In a Binary Options trade the trade get's closed after a specific amount of time and the only thing that matters is if the market has increased in price or decreased after that amount of...
PineScript code:

Pine Script™ strategy
Binary Options Strategy Template
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
//@version=4
strategy("Binary Options Strategy Template", overlay=true)
// In this code we track the bar where a position was opened and close the position
// aftera specified number of bars. The objective of this script is testing long/short signals
// for knowing the amount of times it would turn a profit or not.
// User input for amount of bars till close
barsTillClose = input(5, minval=2, title="Amount of Bars Till Close Position")
// SIMPLE ENTRY LOGIC (insert long/short signal here)
sma = sma(close, 14)
strategy.entry("Long", strategy.long, when=close > sma)
strategy.entry("Short", strategy.long, when=close < sma)
// Track the Entry Bar
entryTime = float(na)
timeClose = bool(na)
entryTime := timeClose[1] ? na : strategy.position_size[0] > strategy.position_size[1] ? bar_index : entryTime[1]
// See if we need to close
timeClose := bar_index >= entryTime+(barsTillClose-2)
strategy.close("Long", when=timeClose)
strategy.close("Short", when=timeClose)
plot(sma)
Expand (28 lines)