Script Name: Cheat Code- Example 1; Short-Term; Follow the Trend
Author: CheatCode1
Description: BINANCE:BTCUSDT ; BINANCE:ETHUSDT ; BINANCE:FILUSDT ;

This strategy is simple and easy to read and takes advantage of conditional signs of trend reversals. It works best in 10-minute time frames for most large and mid-cap crypto. This code is a tutorial for creating a profitable yet easy strategy, and hopefully, it can be put to good use  :)
PineScript code:

Pine Script™ strategy
Cheat Code- Example 1; Short-Term; Follow the Trend
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © cpirkk
//@version=5
//SUBSCRIBE TO CHEAT CODE!!!
//
//
//
//SUBSCRIBE TO CHEAT CODE!!!
strategy("Cheat Codes Example", overlay = true)
//RSI
rsi = ta.rsi(close, 14)
//ENTRY
LC1 = ta.crossover(ta.sma(close,21), ta.sma(close,100))
LC2 = ta.sma(close, 200) > close
if (LC1) and (LC2) 
    strategy.entry("BULL CALL", strategy.long)
    
SC1 = ta.sma(close, 200) < close
SC2 = ta.crossunder(rsi, 55)
if (SC1) and (SC2)
    strategy.entry("BEAR CALL", strategy.short)
    
    // BEST PAIRINGS:
    // BTC: 10M
    // MATIC: 10M
    // ETH: 10M
    // FIL: 10M
    // :) 
Expand (37 lines)