Script Name: Consecutive Up-Down Strat + alerts via TradingConnector to Forex
Author: Peter_O
Description: Software part of algotrading is simpler than you think. TradingView is a great place to do this actually. To present it, I'm publishing each of the default strategies you can find in Pinescript editor's "built-in" list with slight modification - I'm only adding 2 lines of code, which will trigger alerts, ready to be forwarded to your broker via TradingConnector...
PineScript code:

Pine Script™ strategy
Consecutive Up/Down Strat + alerts via TradingConnector to Forex
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
//@version=4
strategy("Consecutive Up/Down Strategy with alerts via TradingConnector to Forex", overlay=true, default_qty_value=1000)
consecutiveBarsUp = input(3)
consecutiveBarsDown = input(3)
price = close
ups = 0.0
ups := price > price[1] ? nz(ups[1]) + 1 : 0
dns = 0.0
dns := price < price[1] ? nz(dns[1]) + 1 : 0
if (ups >= consecutiveBarsUp)
    strategy.entry("ConsUpLE", strategy.long, comment="ConsUpLE")
    alert(message='long', freq=alert.freq_once_per_bar_close)
if (dns >= consecutiveBarsDown)
    strategy.entry("ConsDnSE", strategy.short, comment="ConsUpLE")
    alert(message='short', freq=alert.freq_once_per_bar_close)
//plot(strategy.equity, title="equity", color=color.red, linewidth=2, style=plot.style_areabr)
//Lines of code added to the original built-in script: 12 and 15 only.
//They trigger alerts ready to be executed on real markets through TradingConnector
//available for Forex, indices, crypto, stocks - anything your broker offers for trading via MetaTrader4/5
Expand (21 lines)