Script Name: CROSS_ALGO SYSTEM
Author: himanshumahalle
Description: Crossover Strategy using exponential moving averages with entry and exits.
PineScript code:

Pine Script™ strategy
CROSS_ALGO SYSTEM
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © himanshumahalle
//@version=4
strategy("CROSS_ALGO SYSTEM")
// INPUT CONTROLS
lengthSEMA= input(title="LSEMA", type = input.integer, defval=13,minval=1,maxval=100,step=1)
lengthLEMA= input(title="LLEMA", type = input.integer, defval=50,minval=1,maxval=100,step=1)
//INDICATOR
SEMA= ema(close,lengthSEMA)
LEMA= ema(close,lengthLEMA)
// BUY AND SELL
buy = crossover(SEMA,LEMA)
sell = crossunder(SEMA,LEMA)
//EXITS
buyexit = crossunder(SEMA,LEMA)
sellexit = crossover(SEMA,LEMA)
//EXECUTION
strategy.entry("long",strategy.long,when=buy,comment = "Buy")
strategy.entry("short",strategy.short,when=sell,comment = "Sell")
strategy.close("long",when= buyexit , comment= "Sell")
strategy.close("short",when= sellexit , comment= "Buy")
Expand (38 lines)