Script Name: Donchian Strat EXMO
Author: pskoroplas
Description: This is simple test of Turtle Trading strategy by Richard Dennis. The script meant to place orders on Donchian Channel borders. It's best to test and use on mid-term charts like 1H and more. 

I've chosen Kraken XBT/USDT chart because this market opened in december 2019. The main problem of crypto trading strategy testing is the bullish market of 2017 year. That...
PineScript code:

Pine Script™ strategy
Donchian Strat EXMO
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © pskoroplas
//@version=4
strategy("Donchian Strat EXMO", overlay=true)
long_per = input(defval = 20, title = "Long Period")
h = highest(high, long_per)
l = lowest(low, long_per)
plot(l)
plot(h)
perc = close/100
if h[1] < h[2]
    strategy.order("BUY", true, stop = h)
    //strategy.exit("BUY", profit = 400)
if l[1] > l[2]
    strategy.order("SELL", false, stop = l)
    //strategy.exit("SELL", profit = 400)
Expand (25 lines)