Script Name: EMA Slope AyE
Author: fajardoarelys
Description: We create our own indicator to calculate the slope of a 50 period EMA over the last 3 candles.
PineScript code:

Pine Script™ strategy
EMA Slope AyE
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © fajardoarelys
//@version=4
strategy("EMA Slope AyE", shorttitle="SLOPE", overlay=false)
EMAPeriod = input(50, title = "EMA Period", type = input.integer)
SlopePeriod = input(3, title = "Slope Period", type = input.integer)
EMA = ema(close, EMAPeriod)
Slope = (EMA - EMA[SlopePeriod]) / SlopePeriod
plot(Slope, color = color.yellow, linewidth = 2)
zero = hline(0, "zero", color=#787B86)
Expand (13 lines)