Script Name: EMA12-26 buy spot only
Author: sasinp
Description: Inspire by CDC action zone, all thanks should be given to AJ piranya33
PineScript code:

Pine Script™ strategy
EMA12/26 buy spot only
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © sasinp
//@version=5
strategy("EMA12/26 buy spot only", overlay=true)
longCondition = ta.crossover(ta.ema(close, 12), ta.ema(close, 26))
if (longCondition)
    strategy.entry("buy", strategy.long)
if ta.crossunder(ta.ema(close, 12), ta.ema(close, 26))
    strategy.close("buy")
Expand (13 lines)