Script Name: eswaran ab
Author: ESWARMONK2515
Description: //@version=5
strategy("MACD Strategy", overlay=true)
fastLength = input(12)
slowlength = input(26)
MACDLength = input(9)
MACD = ta.ema(close, fastLength) - ta.ema(close, slowlength)
aMACD = ta.ema(MACD, MACDLength)
delta = MACD - aMACD
if (ta.crossover(delta, 0))
	strategy.entry("MacdLE", strategy.long, comment="MacdLE")
if (ta.crossunder(delta,...
PineScript code:

Pine Script™ strategy
eswaran ab
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0
//Break out trading system works best in a weekly chart and daily chart of Nifty and BankNifty
//@version=4
strategy("Eswar New",shorttitle = "ESW",default_qty_type = strategy.percent_of_equity,default_qty_value = 100, overlay=true)
length = input(20, minval=1)
exit = input(1, minval=1, maxval=2,title = "Exit Option") // Use Option 1 to exit using lower band; Use Option 2 to exit using basis line
lower = lowest(length)
upper = highest(length)
basis = avg(upper, lower)
l = plot(lower, color=color.blue)
u = plot(upper, color=color.blue)
plot(basis, color=color.orange)
fill(u, l, color=color.blue)
longCondition = crossover(close,upper[1])
if (longCondition)
    strategy.entry("Long", strategy.long)
if(exit==1)
    if (crossunder(close,lower[1]))
        strategy.close("Long")
if(exit==2) 
    if (crossunder(close,basis[1]))
        strategy.close("Long")
Expand (30 lines)