Script Name: EURUSD COT Trend Strategy
Author: exlux99
Description: This is a long term/investment type of strategy designed to have a good idea about where the big trend direction is headed.

Its logic, its made entirely on the COT report, mainly from looking into the net non comercial positions aka the speculators.

For bullish trend we look that the difference between long non comercial vs short non comercial is higher than...
PineScript code:

Pine Script™ strategy
EURUSD COT Trend Strategy
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © exlux99
//@version=5
strategy("EURUSD COT Strategy",overlay=true)
long_noncom   = request.security("QUANDL:CFTC/"+'099741'+'_F_L_ALL|1', "W", close) 
short_noncom  = request.security("QUANDL:CFTC/"+'099741'+'_F_L_ALL|2', "W", close) 
net_noncomercial = long_noncom-short_noncom
long = net_noncomercial > 0 
short = net_noncomercial < 0 
strategy.entry("long",strategy.long,when=long)
strategy.entry("short",strategy.short,when=short)
Expand (20 lines)