Script Name: fiveema
Author: Yenchiii
Description: // © CarterTsai
//@version=4
strategy(title="ema_example", shorttitle="ema_example", overlay=true)
plot(ema(close, 12), title="12ema", color=color.white, linewidth=1)
plot(ema(close, 144), title="144ema", color=color.yellow, linewidth=1)
plot(ema(close, 169), title="169ema", color=color.orange, linewidth=1)
plot(ema(close, 576), title="576ema", color=color.blue, ...
PineScript code:

Pine Script™ strategy
fiveema
Copy code
1
2
3
4
5
6
7
8
// © CarterTsai
//@version=4
strategy(title="ema_example", shorttitle="ema_example", overlay=true)
plot(ema(close, 12), title="12ema", color= color.white, linewidth=1)
plot(ema(close, 144), title="144ema", color= color.yellow, linewidth=1)
plot(ema(close, 169), title="169ema", color= color.orange, linewidth=1)
plot(ema(close, 576), title="576ema", color= color.blue,  linewidth=1)
plot(ema(close, 676), title="676ema", color= color.green, linewidth=1)