Script Name: Hourly Bias on BTC in Bullish USA Session “Green Eagle”
Author: TheSocialCryptoClub
Description: Name: Hourly Bias on BTC in Bullish USA Session

Category: Hourly Bias

Operating mode: Spot, only long

Trades duration: Intraday, 11 bars

Timeframe: 1H

Suggested usage: When the market is compressed, USA session has a bullish bias.

Entry: enter Long at 15:00 on specific days of the week. There is a volatility filter based on ATR which identifies...
PineScript code:

Pine Script™ strategy
Hourly Bias on BTC in Bullish USA Session “Green Eagle”
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
// This source code is subject to the terms of the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)
// © TheSocialCryptoClub
//@version=5
strategy("Hourly BIAS on BTCUSDT","Green Eagle",
         overlay=true, 
         initial_capital=10000,
         default_qty_value=10,
         default_qty_type=strategy.percent_of_equity, 
         commission_type=strategy.commission.percent,
         commission_value=0.075, 
         slippage = 1, 
         backtest_fill_limits_assumption = 1)
// Day Filter
day_filter = dayofweek == 1 or dayofweek == 2 or dayofweek == 4 or dayofweek == 6 ? true : false
// Volatility Filter
volatility_filter = ta.atr(2) <= ta.atr(14) ? true : false 
// Entry and Close
if hour==14 and day_filter and volatility_filter
    strategy.entry("EL", strategy.long)
if hour == 0
    strategy.close("EL") 
Expand (25 lines)