Script Name: hà tỷ phú 999
Author: hatnxkld
Description: xin chào chúng tôi rất vui vì có1 chiến lược cho mọi người xem
đầu tiên là cái thứ nhất
sau đó là cái thứ 2
PineScript code:

Pine Script™ strategy
hà tỷ phú 999
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © hatnxkld
//@version=4
strategy("Chiến lược 3EMA giao cắt", overlay=true)
ngan=input(title="Ema ngắn", defval = 12)
plot(ngan, title="EMA ngắn", color=color.yellow)
tb=input(title="Ema trung bình", defval = 48)
plot(tb, title="EMA trung bình", color=color.blue)
dai=input(title="Ema dai", defval = 288)
plot(dai, title="EMA dai", color=color.red)
Expand (12 lines)