Script Name: MA Crossover Alerts
Author: sujay.paranjpe
Description: Create option in Alert dialogue box when MAs cross over
PineScript code:

Pine Script™ strategy
MA Crossover Alerts
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
//@version=4
//study(title="MA Crossover Strategy", overlay = true)
strategy("MA Crossover Alerts", overlay=true)
src = input(close, title="Source")
price = security(syminfo.tickerid, timeframe.period, src)
ma1 = input(25, title="1st MA Length")
type1 = input("SMA", "1st MA Type", options=["SMA", "EMA"])
ma2 = input(50, title="2nd MA Length")
type2 = input("SMA", "2nd MA Type", options=["SMA", "EMA"])
price1 = if type1 == "SMA"
    sma(price, ma1)
else
    ema(price, ma1)
price2 = if type2 == "SMA"
    sma(price, ma2)
else
    ema(price, ma2)
    
alertcondition(crossover(price1, price2), title='Alert! Long Crossover', message='Go Long')
alertcondition(crossunder(price1, price2), title='Alert! Short Crossover', message='Go Short')
Expand (27 lines)