Script Name: MA&AO
Author: TradingAmmo
Description: That is quit simple strategy, which combines only two indicators: AO and MA. The logic of trades is also clear, when AO is bullish; slow ma is under the close price; fast ma > slow ma - buy.
PineScript code:

Pine Script™ strategy
MA&AO
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
//@version=4
strategy("MA&AO", overlay = true, default_qty_type=strategy.percent_of_equity, default_qty_value=100, commission_type=strategy.commission.percent, commission_value=0.075, currency='USD')
startP = timestamp(input(2017, "Start Year"), input(12, "Month"), input(17, "Day"), 0, 0)
end   = timestamp(input(9999, "End Year"),   input(1, "Month"),   input(1, "Day"),   0, 0)
_testPeriod() =>
    iff(time >= startP and time <= end, true, false)
//Inputs
fast_ma = input(13, title="Fast EMA", minval=2)
slow_ma = input(55, minval=1, title="Slow SMA")
AO_fast = input(13, minval=1, title="Awesome Length Fast")
AO_slow = input(21, minval=1, title="Awesome Length Slow")
//MA
fast  = ema(close, fast_ma)
slow =  sma(close, slow_ma)
//AO
AO_1 = sma(hl2, AO_fast)
AO_2 = sma(hl2, AO_slow)
dif = AO_1 - AO_2
AO = dif>=0? dif > dif[1] ? 1 : 2 : dif > dif[1] ? -1 : -2
long   =  crossover(fast, slow) and close > slow and abs(AO)==1
short =   fast < slow and close < slow and abs(AO)==2
long_condition =  long and close > ema(close, 200) and _testPeriod() 
strategy.entry('BUY', strategy.long, when=long_condition)  
 
short_condition = short 
strategy.close('BUY', when=short_condition)
plot(fast, color=color.green)
plot(slow, color=color.red)
Expand (35 lines)