Script Name: MACD Signal with RSI Indicating Strategy
Author: smartstang23
Description: This strategy looks for MACD signal crossover and RSI confirmation of oversold/overbought condition.

Tune to your crypto/stock for best results using the strategy and sent an alert.  Currently set up to use 25% of equity at each buy signal and will sell 1/3 of position at each sell signal.  Initial investment is $1000, but adjust as necessary.

Currently tuned to...
PineScript code:

Pine Script™ strategy
MACD Signal with RSI Indicating Strategy
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
//@version=4
strategy(default_qty_value = 155, pyramiding = 4, title="MACD crossover while RSI Oversold/Overbought", overlay=true, shorttitle="MACD Cross + RSI Oversold Overbought", initial_capital = 1000)
//MACD Settings
fastMA = input(title="Fast moving average", defval = 12, minval = 7) //7 16
slowMA = input(title="Slow moving average", defval = 26, minval = 7) //24 26 
signalLength = input(9,minval=1) //9 6
//RSI settings
RSIOverSold = input(37 ,minval=1) //26
RSIOverBought = input(69 ,minval=1) //77
src = close, len = input(14, minval=1, title="Length")
up = rma(max(change(src), 0), len)
down = rma(-min(change(src), 0), len)
rsi = down == 0 ? 100 : up == 0 ? 0 : 100 - (100 / (1 + up / down))
wasOversold = rsi[0] <= RSIOverSold or rsi[1] <= RSIOverSold or rsi[2] <= RSIOverSold or rsi[3] <= RSIOverSold or rsi[4] <= RSIOverSold or rsi[5] <= RSIOverSold
wasOverbought = rsi[0] >= RSIOverBought or rsi[1] >= RSIOverBought or rsi[2] >= RSIOverBought or rsi[3] >= RSIOverBought or rsi[4] >= RSIOverBought or rsi[5] >= RSIOverBought
[currMacd,_,_] = macd(close[0], fastMA, slowMA, signalLength)
[prevMacd,_,_] = macd(close[1], fastMA, slowMA, signalLength)
signal = ema(currMacd, signalLength)
crossoverBear = cross(currMacd, signal) and currMacd < signal ? avg(currMacd, signal) : na
crossoverBull = cross(currMacd, signal) and currMacd > signal ? avg(currMacd, signal) : na
// Configure backtest start date with inputs
startDate = input(title="Start Date",
     defval=8, minval=1, maxval=31)
startMonth = input(title="Start Month", 
     defval=3, minval=1, maxval=12)
startYear = input(title="Start Year",
     defval=2021, minval=1800, maxval=2100)
afterStartDate = (time >= timestamp(syminfo.timezone, startYear, startMonth, startDate, 0, 0))
sellRate = input(title="Strategy Sell Rate", defval=2, minval=1, maxval=4)
// Make an input to configure the maximum position size
maxPos = input(title="Maximum Position Size", type=input.integer, defval=15000)
// Look how much quantity we can still trade
posToTrade = maxPos - abs(strategy.position_size)
if (afterStartDate==true)
    if (crossoverBull and wasOversold and (posToTrade > 0))
        strategy.order("long", strategy.long)
        myLabel = label.new(x=bar_index, y=low - 0.2*tr, text=tostring(strategy.position_size), color=color.black, textcolor=color.green, style=label.style_labelup)
    if (crossoverBear and wasOverbought)
        strategy.order("long", strategy.short, qty=strategy.position_size*(1/sellRate)) 
        myLabel = label.new(x=bar_index, y=high + 0.2*tr, text=tostring(strategy.position_size), color=color.black, textcolor=color.red, style=label.style_labeldown)
//plot(strategy.netprofit)
Expand (53 lines)