Script Name: Mechanical Trading Strategy
Author: manan5439
Description: The "Mechanical Trading Strategy" is a simple and systematic approach to trading that aims to capture short-term price movements in the financial markets. This strategy focuses on executing trades based on specific conditions and predetermined profit targets and stop loss levels.

Key Features:

Profit Target: The strategy allows you to set a profit target as a...
PineScript code:

Pine Script™ strategy
Mechanical Trading Strategy
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
//@version=5
strategy("Mechanical Trading Strategy", overlay=true)
profitTarget = input(0.4, "Profit Target (%)") / 100
stopLoss = input(0.2, "Stop Loss (%)") / 100
tradeHour = input(16, "Enter Hour you want to trade every day")
isShort = input(false, "check this box if you want to test short/selling trade")
entryPrice = close
if (hour(time) == tradeHour)
    if(isShort)
        takeProfitLevel = entryPrice - (entryPrice * profitTarget)
        stopLossLevel =  entryPrice + (entryPrice * stopLoss)
        strategy.entry("Sell", strategy.short)
        strategy.exit("Take Profit", "Sell", limit=takeProfitLevel,stop = stopLossLevel)
    else
        takeProfitLevel = entryPrice + (entryPrice * profitTarget)
        stopLossLevel =  entryPrice - (entryPrice * stopLoss)
        strategy.entry("Buy", strategy.long)
        strategy.exit("Take Profit", "Buy", limit=takeProfitLevel,stop = stopLossLevel)
Expand (25 lines)