Script Name: Noro's SRSI Strategy
Author: ROBO_Trading
Description: Indicator 
Blue line - common RSI indicator.
Red line - SMA based on RSI
Upper black line - 50% + limit (custom parameter, 65% by default)
Lower black line - 50% - limit (custom parameter, 35% by default)

 Strategy 
If the red line (SMA) is higher than the upper black line, open a long position (and close the short position).
If the red line (SMA) is lower than...
PineScript code:

Pine Script™ strategy
Noro's SRSI Strategy
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
//@version=4
strategy(title = "Noro's SRSI Strategy", shorttitle = "SRSI", overlay = false, default_qty_type = strategy.percent_of_equity, default_qty_value = 100, initial_capital = 100, commission_value = 0.1)
//Settings
lenrsi = input(14, minval = 2, title = "RSI Length")
lensma = input(10, minval = 2, title = "SMA Length")
limit  = input(15, minval = 0, title = "RSI Limit, %")
//Indicator
rsi = rsi(close, lenrsi)
sma = sma(rsi, lensma)
plot(rsi, transp = 0, color = color.blue)
plot(sma, transp = 0, color = color.red)
plot(50 + limit, transp = 0, color = color.black)
plot(50 - limit, transp = 0, color = color.black)
//Trading
if sma > 50 + limit
    strategy.entry("Long", strategy.long)
if sma < 50 - limit
    strategy.entry("Short", strategy.short)
Expand (22 lines)