Script Name: Simple and efficient PSAR swing strategy
Author: SoftKill21
Description: This is a strategy build inside tradingview, which I found it works great with swing/position trading.

It works based on parabolic sar indicator, when indicator is below the candle, is an uptrend and when its its above is a downtrend.

At the same time it's very nice, because it has a sort of stop loss which is dynamic, because it triggers when candle crosses...
PineScript code:

Pine Script™ strategy
Simple and efficient PSAR swing strategy
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
//@version=4
strategy("Swing Parabolic SAR Strategy", overlay=true)
start = input(0.02)
increment = input(0.02)
maximum = input(0.2)
var bool uptrend = na
var float EP = na
var float SAR = na
var float AF = start
var float nextBarSAR = na
//MONEY MANAGEMENT--------------------------------------------------------------
balance = strategy.netprofit + strategy.initial_capital //current balance
floating = strategy.openprofit          //floating profit/loss
risk = input(1,type=input.float,title="Risk %")/100           //risk % per trade
if bar_index > 0
    firstTrendBar = false
    SAR := nextBarSAR
    if bar_index == 1
        float prevSAR = na
        float prevEP = na
        lowPrev = low[1]
        highPrev = high[1]
        closeCur = close
        closePrev = close[1]
        if closeCur > closePrev
            uptrend := true
            EP := high
            prevSAR := lowPrev
            prevEP := high
        else
            uptrend := false
            EP := low
            prevSAR := highPrev
            prevEP := low
        firstTrendBar := true
        SAR := prevSAR + start * (prevEP - prevSAR)
    if uptrend
        if SAR > low
            firstTrendBar := true
            uptrend := false
            SAR := max(EP, high)
            EP := low
            AF := start
    else
        if SAR < high
            firstTrendBar := true
            uptrend := true
            SAR := min(EP, low)
            EP := high
            AF := start
    if not firstTrendBar
        if uptrend
            if high > EP
                EP := high
                AF := min(AF + increment, maximum)
        else
            if low < EP
                EP := low
                AF := min(AF + increment, maximum)
    if uptrend
        SAR := min(SAR, low[1])
        if bar_index > 1
            SAR := min(SAR, low[2])
    else
        SAR := max(SAR, high[1])
        if bar_index > 1
            SAR := max(SAR, high[2])
    nextBarSAR := SAR + AF * (EP - SAR)
    if barstate.isconfirmed
        if uptrend
            //dataL = (close-SAR)*100000
            dataS = (SAR-close)*1000
            
                //Calculate the size of the next trade
            temp01 = balance * risk     //Risk in USD
            temp02 = temp01/dataS        //Risk in lots
            temp03 = temp02*100000      //Convert to contracts
            size = temp03 - temp03%1000 //Normalize to 1000s (Trade size)
            if(size < 1000)
                size := 1000           //Set min. lot size
            strategy.entry("short", strategy.short,size, stop=nextBarSAR, comment="short")
            //strategy.exit("tp/sl short","short",stop=dataS)
            strategy.cancel("long")
        else
            dataL = (close-SAR)*1000
            //dataS = (SAR-close)*100000
            
                //Calculate the size of the next trade
            temp01 = balance * risk     //Risk in USD
            temp02 = temp01/dataL        //Risk in lots
            temp03 = temp02*100000      //Convert to contracts
            size = temp03 - temp03%1000 //Normalize to 1000s (Trade size)
            if(size < 1000)
                size := 1000           //Set min. lot size
            strategy.entry("long", strategy.long,size, stop=nextBarSAR, comment="long")
            //strategy.exit("tp/sl LONG","long",stop=dataL)
            strategy.cancel("short")
            
plot(SAR, style=plot.style_cross, linewidth=3, color=color.orange)
plot(nextBarSAR, style=plot.style_cross, linewidth=3, color=color.aqua)
    
Expand (108 lines)