Script Name: Triple EMA Cross JS
Author: Its_jesse43
Description: Strategy that indicates potential buy and sell signals.
PineScript code:

Pine Script™ strategy
Triple EMA Cross JS
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
//@version=2
strategy("Triple EMA Cross", overlay = true)
a = ema(close, 8)
b = ema(close, 20)
c = ema(close, 50)
plot(a, "ema8", color = yellow, linewidth = 2)
plot(b, "ema20", color = blue, linewidth = 2)
plot(c, "ema50", color = red, linewidth = 2)
long = a > c and a > b and b > c
short = a < c and a < b and b < c
start = timestamp(2019, 1, 1, 0, 0)
if time >= start and time
    strategy.entry("long", strategy.long, 50000.0, when = long)
    strategy.entry("short", strategy.short, 50000.0, when = short)
strategy.close("long", when = a < b)
strategy.close("short", when = a > b)
Expand (26 lines)